"""The generated-code format pairing contract, held across all three ports.

Pairing is on the generated-code FORMAT, never on the release string: a
validator generated by one release keeps importing against a later runtime for
as long as the emitted shape is unchanged. Three runtimes and three emitters
implement that independently, so the facts below are cross-port facts and belong
here rather than in any one port's suite:

- the accepted format range every runtime declares;
- the refusal text every runtime renders, byte for byte;
- the declaration key names every emitter writes into generated code, byte for
  byte;
- the emitted shape itself, pinned, so a change to what the emitters write
  cannot ship without bumping the format the runtimes accept.
"""

from __future__ import annotations

import pytest

from harness import pairing


@pytest.fixture(scope="module")
def observed() -> dict[str, pairing.PortPairing]:
    return pairing.observe_all()


@pytest.fixture(scope="module")
def emitted() -> dict[str, str]:
    return pairing.emit_sources()


def test_accepted_format_range_is_in_lockstep(observed):
    ranges = {p.port: (p.min_format, p.max_format) for p in observed.values()}
    assert len(set(ranges.values())) == 1, (
        f"the runtimes read different generated-code formats: {ranges}; "
        "the accepted range is one cross-port fact and moves in every port at once"
    )
    lo, hi = next(iter(ranges.values()))
    assert 1 <= lo <= hi


def test_refusal_text_is_byte_identical_across_ports(observed):
    for field in ("unread_format_message", "absent_format_message"):
        texts = {p.port: getattr(p, field) for p in observed.values()}
        assert len(set(texts.values())) == 1, (
            f"{field} differs across ports: {texts}"
        )


def test_refusal_text_names_both_sides_and_the_remedy(observed):
    port = observed["go"]
    unread = port.unread_format_message
    assert unread.startswith("strictspec generated-code format mismatch:\n")
    assert f"generated-code format: {port.max_format + 1}\n" in unread
    assert f"runtime reads:         {port.min_format}..{port.max_format}\n" in unread
    assert f"generated by:          {pairing.PROBE_GENERATED_BY}\n" in unread
    assert f"runtime:               {port.version}\n" in unread
    assert unread.endswith(
        "remediation:           regenerate with `strictspec gen` against the current runtime"
    )
    # Generated code that predates the format declaration is REFUSED, never read
    # as format 1: the absence is named, and the remedy is the same regeneration.
    absent = port.absent_format_message
    assert "generated-code format: absent (predates the format declaration)\n" in absent
    assert absent.endswith(
        "remediation:           regenerate with `strictspec gen` against the current runtime"
    )


def test_emitted_declaration_keys_are_byte_identical_across_targets(emitted, observed):
    """Every emitter writes the SAME declaration names, so a consumer reading a
    generated file reads the same keys whatever language it was generated for.
    """
    for key in ("GENERATED_BY", "GENERATED_CODE_FORMAT", "SCHEMA_FORMAT_VERSION"):
        values = {
            lang: pairing.declared_constant(src, key) for lang, src in emitted.items()
        }
        assert len(set(values.values())) == 1, f"{key} differs across targets: {values}"

    emitted_format = int(pairing.declared_constant(emitted["go"], "GENERATED_CODE_FORMAT"))
    accepted = {p.port: (p.min_format, p.max_format) for p in observed.values()}
    for port, (lo, hi) in accepted.items():
        assert lo <= emitted_format <= hi, (
            f"the generator emits format {emitted_format}, which the {port} runtime "
            f"does not read ({lo}..{hi}); generator and runtimes ship as one release"
        )


def test_generated_code_declares_a_release_that_is_not_the_contract(emitted, observed):
    """GENERATED_BY stays in the file as information. The pairing guard call the
    emitters write passes the FORMAT, so no runtime can pair on the release
    string, and no external tool may derive a dependency floor from it.
    """
    calls = {
        "go": "strictspec.RequireGeneratedCodeFormat(GENERATED_CODE_FORMAT, GENERATED_BY)",
        "python": "strictspec.require_generated_code_format(GENERATED_CODE_FORMAT, GENERATED_BY)",
        "ts": "requireGeneratedCodeFormat(GENERATED_CODE_FORMAT, GENERATED_BY)",
    }
    for lang, call in calls.items():
        assert call in emitted[lang], f"{lang} generated code does not call {call}"
    release = pairing.declared_constant(emitted["python"], "GENERATED_BY").strip('"')
    assert release == observed["go"].version


def test_emitted_shape_pin_forces_a_format_bump(emitted, observed):
    """The bump discipline, mechanically.

    The pin records the emitted shape of every target (hashed with the
    generating release normalized away, so a release bump never moves it). If
    this fails, the emitters write something different than they did when the
    pin was taken: bump the generated-code format in the runtimes, then update
    the pin in the same commit.
    """
    pin = pairing.read_pin()
    got = {lang: pairing.shape_hash(src) for lang, src in emitted.items()}
    assert got == pin["shapes"], (
        "the emitted shape changed. Generated code in the wild was written to the "
        "old shape, so the runtimes must stop reading it: bump "
        "MaxGeneratedCodeFormat / MAX_GENERATED_CODE_FORMAT (and the minimum, if "
        "the old shape is no longer read) in every port, then record the new "
        f"format and hashes in {pairing.PIN_PATH.name}.\n"
        f"pinned: {pin['shapes']}\n   got: {got}"
    )
    accepted_max = {p.max_format for p in observed.values()}
    assert pin["generated_code_format"] in accepted_max, (
        "the pin records a generated-code format no runtime writes; the pin and "
        "the runtimes move together"
    )
