"""The generated strictspec error-code catalogue.

Code generated by scripts/gencodes.py from spec/appendix-error-codes.md. DO NOT EDIT.

Every STRICTSPEC_* code with its area, message template, and declared slots,
parsed from the single normative source. Hand-transcription is forbidden; a
freshness test regenerates and byte-compares (drift = failure).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum


class SlotType(IntEnum):
    """One of the slot-type vocabulary of appendix-error-codes.md sec.2."""

    STRING = 0
    INT = 1
    CODE = 2
    IDENTIFIER = 3
    VERSION = 4
    PATH = 5
    VALUE = 6
    LIST = 7

    def __str__(self) -> str:
        return _SLOT_TYPE_NAMES.get(self, "unknown")


_SLOT_TYPE_NAMES = {
    SlotType.STRING: "string",
    SlotType.INT: "int",
    SlotType.CODE: "code",
    SlotType.IDENTIFIER: "identifier",
    SlotType.VERSION: "version",
    SlotType.PATH: "path",
    SlotType.VALUE: "value",
    SlotType.LIST: "list",
}


@dataclass(frozen=True)
class SlotSpec:
    """One declared slot: its placeholder name and declared type. For LIST,
    elem_type is the element type (e.g. list<string>).
    """

    name: str
    type: SlotType
    elem_type: SlotType | None = None


@dataclass(frozen=True)
class Entry:
    """One catalogue row: the code, its area, the pinned message template, and
    the slots the template interpolates in placeholder order.
    """

    code: str
    area: str
    template: str
    slots: tuple[SlotSpec, ...] = ()


def lookup(code: str) -> Entry | None:
    """Return the catalogue entry for a code, or None."""
    return CATALOGUE.get(code)


def all_entries() -> list[Entry]:
    """Every catalogue entry, sorted by code."""
    return [CATALOGUE[k] for k in sorted(CATALOGUE)]


# The closed area set (appendix-error-codes.md section 3).
AREAS = (
    'ALIAS',
    'CHANNEL',
    'CROSS',
    'DEPTH',
    'DIFF',
    'DOCDIFF',
    'ENUMSRC',
    'GATE',
    'IMPORT',
    'INTRA',
    'KEY',
    'MANIFEST',
    'METAGATE',
    'MIGRATE',
    'NUM',
    'PARSE',
    'SCALAR',
    'SCHEMA',
    'SERIALIZE',
    'TYPE',
    'UNION',
    'VALUE',
)

CATALOGUE: dict[str, Entry] = {
    'STRICTSPEC_ALIAS_BOTH_PRESENT': Entry(
        code='STRICTSPEC_ALIAS_BOTH_PRESENT',
        area='ALIAS',
        template='Both {alias} and canonical {canonical} are present at {path}; provide exactly one.',
        slots=(
            SlotSpec('alias', SlotType.IDENTIFIER),
            SlotSpec('canonical', SlotType.IDENTIFIER),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_CHANNEL_VERSION_REFUSED': Entry(
        code='STRICTSPEC_CHANNEL_VERSION_REFUSED',
        area='CHANNEL',
        template='Cannot open channel for schema {schema}: peer offers `format_version` {got}, this endpoint speaks only {expected}. Update the client to the paired strictspec release ({release}).',
        slots=(
            SlotSpec('schema', SlotType.IDENTIFIER),
            SlotSpec('got', SlotType.VERSION),
            SlotSpec('expected', SlotType.VERSION),
            SlotSpec('release', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_CROSS_COLLECTION_UNIQUE': Entry(
        code='STRICTSPEC_CROSS_COLLECTION_UNIQUE',
        area='CROSS',
        template='Value {value} at {path} also appears in {source}; it must be unique across the collection family.',
        slots=(
            SlotSpec('value', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('source', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_CROSS_COUNT_LIMIT': Entry(
        code='STRICTSPEC_CROSS_COUNT_LIMIT',
        area='CROSS',
        template='Collection at {path} has {actual} elements across {source}; the limit is {limit}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.INT),
            SlotSpec('source', SlotType.STRING),
            SlotSpec('limit', SlotType.INT),
        ),
    ),
    'STRICTSPEC_CROSS_REFERENCE_UNRESOLVED': Entry(
        code='STRICTSPEC_CROSS_REFERENCE_UNRESOLVED',
        area='CROSS',
        template='Reference {value} at {path} does not resolve in {source}.',
        slots=(
            SlotSpec('value', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('source', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_CROSS_RESOLVER_UNAVAILABLE': Entry(
        code='STRICTSPEC_CROSS_RESOLVER_UNAVAILABLE',
        area='CROSS',
        template='Constraint at {path} requires evidence resolver {source}, which this environment cannot satisfy.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('source', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_CROSS_SET_COVERAGE': Entry(
        code='STRICTSPEC_CROSS_SET_COVERAGE',
        area='CROSS',
        template='Element {value} of {source} is not covered by the collection at {path}.',
        slots=(
            SlotSpec('value', SlotType.VALUE),
            SlotSpec('source', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_CROSS_SUM_FIELD_MISSING': Entry(
        code='STRICTSPEC_CROSS_SUM_FIELD_MISSING',
        area='CROSS',
        template='sum-limit at {path} over {source} requires numeric field {field} on every selected document; document {actual} lacks it or has a non-numeric value.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('source', SlotType.STRING),
            SlotSpec('field', SlotType.STRING),
            SlotSpec('actual', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_CROSS_SUM_LIMIT': Entry(
        code='STRICTSPEC_CROSS_SUM_LIMIT',
        area='CROSS',
        template='Sum of {field} across {source} at {path} is {actual}; the limit is {limit}.',
        slots=(
            SlotSpec('field', SlotType.STRING),
            SlotSpec('source', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('limit', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_DEPTH_EXCEEDED': Entry(
        code='STRICTSPEC_DEPTH_EXCEEDED',
        area='DEPTH',
        template='Document nesting at {path} exceeds the maximum validation depth of {limit}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('limit', SlotType.INT),
        ),
    ),
    'STRICTSPEC_DIFF_ADJUDICATION_INVALID': Entry(
        code='STRICTSPEC_DIFF_ADJUDICATION_INVALID',
        area='DIFF',
        template='Adjudication file {source} does not validate against the adjudication schema: {detail}.',
        slots=(
            SlotSpec('source', SlotType.STRING),
            SlotSpec('detail', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_DIFF_ADJUDICATION_MISSING': Entry(
        code='STRICTSPEC_DIFF_ADJUDICATION_MISSING',
        area='DIFF',
        template='Claim {condition} is corpus-supported without a corpus, and no adjudication entry covers it.',
        slots=(
            SlotSpec('condition', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_DIFF_CORPUS_EMPTY': Entry(
        code='STRICTSPEC_DIFF_CORPUS_EMPTY',
        area='DIFF',
        template='The corpus glob {source} resolved to zero documents; `diff` requires a non-empty corpus.',
        slots=(
            SlotSpec('source', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_DIFF_NARROWING_UNBUMPED': Entry(
        code='STRICTSPEC_DIFF_NARROWING_UNBUMPED',
        area='DIFF',
        template='Document {source} is valid under the old schema but invalid under the new schema at the same `format_version` {expected}; this narrowing requires a version bump.',
        slots=(
            SlotSpec('source', SlotType.STRING),
            SlotSpec('expected', SlotType.VERSION),
        ),
    ),
    'STRICTSPEC_DIFF_TAXONOMY_MISDECLARED': Entry(
        code='STRICTSPEC_DIFF_TAXONOMY_MISDECLARED',
        area='DIFF',
        template='Op {op} is declared {expected} but the corpus shows it is {actual}.',
        slots=(
            SlotSpec('op', SlotType.STRING),
            SlotSpec('expected', SlotType.STRING),
            SlotSpec('actual', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_DIFF_VIOLATED': Entry(
        code='STRICTSPEC_DIFF_VIOLATED',
        area='DIFF',
        template='Claim {condition} is VIOLATED: corpus document {source} is a counterexample.',
        slots=(
            SlotSpec('condition', SlotType.STRING),
            SlotSpec('source', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_DOCDIFF_INVALID_OPERAND': Entry(
        code='STRICTSPEC_DOCDIFF_INVALID_OPERAND',
        area='DOCDIFF',
        template='Operand {source} does not validate against the schema; `doc-diff` compares valid documents.',
        slots=(
            SlotSpec('source', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_DOCDIFF_SCHEMA_MISMATCH': Entry(
        code='STRICTSPEC_DOCDIFF_SCHEMA_MISMATCH',
        area='DOCDIFF',
        template='Documents {source} and {actual} do not share `format_version`; `doc-diff` compares documents of one schema at one version.',
        slots=(
            SlotSpec('source', SlotType.STRING),
            SlotSpec('actual', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_ENUMSRC_BAD_SELECTOR': Entry(
        code='STRICTSPEC_ENUMSRC_BAD_SELECTOR',
        area='ENUMSRC',
        template='Enum-source selector {selector} at {path} does not resolve within {source}.',
        slots=(
            SlotSpec('selector', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('source', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_ENUMSRC_MISSING_SOURCE': Entry(
        code='STRICTSPEC_ENUMSRC_MISSING_SOURCE',
        area='ENUMSRC',
        template='Enum at {path} sources arms from {source}, which does not exist.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('source', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_ENUMSRC_SOURCE_NOT_STRINGS': Entry(
        code='STRICTSPEC_ENUMSRC_SOURCE_NOT_STRINGS',
        area='ENUMSRC',
        template='Enum source {source} at {path} yields a non-string arm; sourced enum arms must be strings.',
        slots=(
            SlotSpec('source', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_ENUMSRC_STALE': Entry(
        code='STRICTSPEC_ENUMSRC_STALE',
        area='ENUMSRC',
        template='Baked enum arms at {path} differ from source {source}; regenerate with `strictspec gen`. Baked: {baked}. Source: {actual}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('source', SlotType.STRING),
            SlotSpec('baked', SlotType.LIST, SlotType.STRING),
            SlotSpec('actual', SlotType.LIST, SlotType.STRING),
        ),
    ),
    'STRICTSPEC_GATE_ABSENT': Entry(
        code='STRICTSPEC_GATE_ABSENT',
        area='GATE',
        template='Document is missing `format_version`. Schema {schema} expects {expected}. Run: {invocation}',
        slots=(
            SlotSpec('schema', SlotType.IDENTIFIER),
            SlotSpec('expected', SlotType.VERSION),
            SlotSpec('invocation', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_GATE_UNSUPPORTED': Entry(
        code='STRICTSPEC_GATE_UNSUPPORTED',
        area='GATE',
        template='Document `format_version` is {got}, but schema {schema} accepts exactly {expected} (migration set {migset}). Run: {invocation}',
        slots=(
            SlotSpec('got', SlotType.VERSION),
            SlotSpec('schema', SlotType.IDENTIFIER),
            SlotSpec('expected', SlotType.VERSION),
            SlotSpec('migset', SlotType.IDENTIFIER),
            SlotSpec('invocation', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_GATE_WRONG_TYPE': Entry(
        code='STRICTSPEC_GATE_WRONG_TYPE',
        area='GATE',
        template='Document `format_version` must be an integer; got {got}. Schema {schema} expects {expected}. Run: {invocation}',
        slots=(
            SlotSpec('got', SlotType.VALUE),
            SlotSpec('schema', SlotType.IDENTIFIER),
            SlotSpec('expected', SlotType.VERSION),
            SlotSpec('invocation', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_IMPORT_CROSS_FILE_CONSTRAINT': Entry(
        code='STRICTSPEC_IMPORT_CROSS_FILE_CONSTRAINT',
        area='IMPORT',
        template='Imported file {file} declares a constraint; type-definition files may declare types only, not constraints.',
        slots=(
            SlotSpec('file', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_IMPORT_MISSING_TYPE_FILE': Entry(
        code='STRICTSPEC_IMPORT_MISSING_TYPE_FILE',
        area='IMPORT',
        template='Type-definition file {file} imported by {schema} does not exist.',
        slots=(
            SlotSpec('file', SlotType.STRING),
            SlotSpec('schema', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_IMPORT_TRANSITIVE': Entry(
        code='STRICTSPEC_IMPORT_TRANSITIVE',
        area='IMPORT',
        template='Type-definition file {file} imports another file; transitive imports are not permitted.',
        slots=(
            SlotSpec('file', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_IMPORT_UNKNOWN_TYPE': Entry(
        code='STRICTSPEC_IMPORT_UNKNOWN_TYPE',
        area='IMPORT',
        template='Type {name} is not defined in imported file {file}.',
        slots=(
            SlotSpec('name', SlotType.IDENTIFIER),
            SlotSpec('file', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_AT_LEAST_ONE_OF': Entry(
        code='STRICTSPEC_INTRA_AT_LEAST_ONE_OF',
        area='INTRA',
        template='At least one of {fields} must be present at {path}; none were.',
        slots=(
            SlotSpec('fields', SlotType.LIST, SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_INTRA_COLLECTIONS_DISJOINT': Entry(
        code='STRICTSPEC_INTRA_COLLECTIONS_DISJOINT',
        area='INTRA',
        template='Arrays {fields} at {path} must share no element; {value} appears in both (normalization: {normalization}).',
        slots=(
            SlotSpec('fields', SlotType.LIST, SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('value', SlotType.VALUE),
            SlotSpec('normalization', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_CONDITIONAL_REQUIRED': Entry(
        code='STRICTSPEC_INTRA_CONDITIONAL_REQUIRED',
        area='INTRA',
        template='Field {key} at {path} is required when {condition}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('condition', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_CONDITIONAL_VALUE': Entry(
        code='STRICTSPEC_INTRA_CONDITIONAL_VALUE',
        area='INTRA',
        template='Field {key} at {path} must equal {expected} when {condition}; got {got}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.VALUE),
            SlotSpec('condition', SlotType.STRING),
            SlotSpec('got', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_INTRA_CO_PRESENCE': Entry(
        code='STRICTSPEC_INTRA_CO_PRESENCE',
        area='INTRA',
        template='Fields {fields} at {path} must be present together or absent together; found {actual}.',
        slots=(
            SlotSpec('fields', SlotType.LIST, SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.LIST, SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_EXACTLY_ONE_OF': Entry(
        code='STRICTSPEC_INTRA_EXACTLY_ONE_OF',
        area='INTRA',
        template='Exactly one of {fields} must be present at {path}; found {actual}.',
        slots=(
            SlotSpec('fields', SlotType.LIST, SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.LIST, SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_FORBIDDEN_WHEN': Entry(
        code='STRICTSPEC_INTRA_FORBIDDEN_WHEN',
        area='INTRA',
        template='Field {key} at {path} is forbidden when {condition}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('condition', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_MUTUAL_EXCLUSION': Entry(
        code='STRICTSPEC_INTRA_MUTUAL_EXCLUSION',
        area='INTRA',
        template='Fields {fields} at {path} are mutually exclusive; found {actual}.',
        slots=(
            SlotSpec('fields', SlotType.LIST, SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.LIST, SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_ORDERED_PAIR': Entry(
        code='STRICTSPEC_INTRA_ORDERED_PAIR',
        area='INTRA',
        template='Field {actual} at {path} must be less than sibling {value}.',
        slots=(
            SlotSpec('actual', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('value', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_PAIRWISE_DISTINCT': Entry(
        code='STRICTSPEC_INTRA_PAIRWISE_DISTINCT',
        area='INTRA',
        template='Values at {path} must be pairwise distinct; {value} repeats (normalization: {normalization}).',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('value', SlotType.VALUE),
            SlotSpec('normalization', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_INTRA_RANGES_DISJOINT': Entry(
        code='STRICTSPEC_INTRA_RANGES_DISJOINT',
        area='INTRA',
        template='Half-open ranges at {path} overlap: {value} intersects {actual}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('value', SlotType.VALUE),
            SlotSpec('actual', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_INTRA_REFERENCE_UNRESOLVED': Entry(
        code='STRICTSPEC_INTRA_REFERENCE_UNRESOLVED',
        area='INTRA',
        template='Reference {value} at {path} does not resolve within the document.',
        slots=(
            SlotSpec('value', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_INTRA_UNIQUE_BY': Entry(
        code='STRICTSPEC_INTRA_UNIQUE_BY',
        area='INTRA',
        template='Duplicate value {value} for unique-by {field} at {path} (normalization: {normalization}).',
        slots=(
            SlotSpec('value', SlotType.VALUE),
            SlotSpec('field', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('normalization', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_KEY_DUPLICATE': Entry(
        code='STRICTSPEC_KEY_DUPLICATE',
        area='KEY',
        template='Duplicate key {key} at {path}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_KEY_UNKNOWN': Entry(
        code='STRICTSPEC_KEY_UNKNOWN',
        area='KEY',
        template='Unknown key {key} at {path}.{suggestion}',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('suggestion', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_MANIFEST_ALREADY_EXISTS': Entry(
        code='STRICTSPEC_MANIFEST_ALREADY_EXISTS',
        area='MANIFEST',
        template='A `strictspec.toml` already exists at {path}; `strictspec init` refuses to overwrite it.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_MANIFEST_DRIFT': Entry(
        code='STRICTSPEC_MANIFEST_DRIFT',
        area='MANIFEST',
        template='Generated output at {path} differs from a fresh generation; run `strictspec gen` and commit.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_MANIFEST_GENERATED_PATH_DIRTY': Entry(
        code='STRICTSPEC_MANIFEST_GENERATED_PATH_DIRTY',
        area='MANIFEST',
        template='Generated path {path} has uncommitted local edits; regenerate before proceeding.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_MANIFEST_PAIRING_MISMATCH': Entry(
        code='STRICTSPEC_MANIFEST_PAIRING_MISMATCH',
        area='MANIFEST',
        template='Runtime version {actual} does not match generated-code version {expected}; regenerate against the paired release.',
        slots=(
            SlotSpec('actual', SlotType.VERSION),
            SlotSpec('expected', SlotType.VERSION),
        ),
    ),
    'STRICTSPEC_MANIFEST_UNKNOWN_RESOLVER': Entry(
        code='STRICTSPEC_MANIFEST_UNKNOWN_RESOLVER',
        area='MANIFEST',
        template='Manifest / schema references evidence resolver {name}, which is not in the resolver vocabulary.',
        slots=(
            SlotSpec('name', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_MANIFEST_UNKNOWN_STORE': Entry(
        code='STRICTSPEC_MANIFEST_UNKNOWN_STORE',
        area='MANIFEST',
        template='Manifest declares store {name}, whose kind {got} is not a recognized store kind.',
        slots=(
            SlotSpec('name', SlotType.IDENTIFIER),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_METAGATE_ABSENT': Entry(
        code='STRICTSPEC_METAGATE_ABSENT',
        area='METAGATE',
        template='Schema {schema} is missing `meta_version`. This strictspec release expects {expected}. Run: {invocation}',
        slots=(
            SlotSpec('schema', SlotType.IDENTIFIER),
            SlotSpec('expected', SlotType.VERSION),
            SlotSpec('invocation', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_METAGATE_UNSUPPORTED': Entry(
        code='STRICTSPEC_METAGATE_UNSUPPORTED',
        area='METAGATE',
        template='Schema {schema} declares `meta_version` {got}, but this strictspec release supports {expected}. Run: {invocation}',
        slots=(
            SlotSpec('schema', SlotType.IDENTIFIER),
            SlotSpec('got', SlotType.VERSION),
            SlotSpec('expected', SlotType.VERSION),
            SlotSpec('invocation', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_METAGATE_WRONG_TYPE': Entry(
        code='STRICTSPEC_METAGATE_WRONG_TYPE',
        area='METAGATE',
        template='Schema `meta_version` must be an integer; got {got}.',
        slots=(
            SlotSpec('got', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_MIGRATE_COLLISION': Entry(
        code='STRICTSPEC_MIGRATE_COLLISION',
        area='MIGRATE',
        template='Migration op {op} would write {path}, which already exists.',
        slots=(
            SlotSpec('op', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_MIGRATE_IRREVERSIBLE_DOWN': Entry(
        code='STRICTSPEC_MIGRATE_IRREVERSIBLE_DOWN',
        area='MIGRATE',
        template='Op {op} at {path} is declared irreversible; a down-migration was requested.',
        slots=(
            SlotSpec('op', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_MIGRATE_ON_CURRENT': Entry(
        code='STRICTSPEC_MIGRATE_ON_CURRENT',
        area='MIGRATE',
        template='Document at {path} is already at the current `format_version` {expected}; nothing to migrate.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.VERSION),
        ),
    ),
    'STRICTSPEC_MIGRATE_PREDICATE_UNSUPPORTED': Entry(
        code='STRICTSPEC_MIGRATE_PREDICATE_UNSUPPORTED',
        area='MIGRATE',
        template='Predicate at {path} tests more than equality and presence; migration predicates are restricted.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_MIGRATE_REVALIDATION_FAILED': Entry(
        code='STRICTSPEC_MIGRATE_REVALIDATION_FAILED',
        area='MIGRATE',
        template='Migrated document at {path} does not validate at `format_version` {expected}; the migration is unsound.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.VERSION),
        ),
    ),
    'STRICTSPEC_MIGRATE_TARGET_MISSING': Entry(
        code='STRICTSPEC_MIGRATE_TARGET_MISSING',
        area='MIGRATE',
        template='Migration op {op} targets {path}, which is absent in the document.',
        slots=(
            SlotSpec('op', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_MIGRATE_TYPE_MISMATCH': Entry(
        code='STRICTSPEC_MIGRATE_TYPE_MISMATCH',
        area='MIGRATE',
        template='Migration op {op} at {path} expected {expected}, found {got}.',
        slots=(
            SlotSpec('op', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.STRING),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_MIGRATE_UNKNOWN_SET': Entry(
        code='STRICTSPEC_MIGRATE_UNKNOWN_SET',
        area='MIGRATE',
        template='No migration set {migset} is registered for schema {schema}.',
        slots=(
            SlotSpec('migset', SlotType.IDENTIFIER),
            SlotSpec('schema', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_MIGRATE_UNWRAP_NOT_SINGLETON': Entry(
        code='STRICTSPEC_MIGRATE_UNWRAP_NOT_SINGLETON',
        area='MIGRATE',
        template='unwrap_singleton at {path} requires a single-element array; found {actual} elements.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.INT),
        ),
    ),
    'STRICTSPEC_NUM_FLOAT_OVERFLOW': Entry(
        code='STRICTSPEC_NUM_FLOAT_OVERFLOW',
        area='NUM',
        template='Float lexeme {actual} at {path} is beyond float64 range.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_NUM_INT_OVERFLOW': Entry(
        code='STRICTSPEC_NUM_INT_OVERFLOW',
        area='NUM',
        template='Integer lexeme {actual} at {path} overflows int64.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_NUM_NON_FINITE': Entry(
        code='STRICTSPEC_NUM_NON_FINITE',
        area='NUM',
        template='Non-finite number {actual} at {path} is not permitted.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_NUM_SAFE_INTEGER': Entry(
        code='STRICTSPEC_NUM_SAFE_INTEGER',
        area='NUM',
        template='Integer {actual} at {path} exceeds the safe-integer range (|n| >= 2^53) required by `safe_integers`.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_NUM_UNREPRESENTABLE': Entry(
        code='STRICTSPEC_NUM_UNREPRESENTABLE',
        area='NUM',
        template='Lexeme {actual} at {path} cannot be represented exactly as float64; the `number` scalar refuses silent precision loss.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_PARSE_JSONL_BLANK_LINE': Entry(
        code='STRICTSPEC_PARSE_JSONL_BLANK_LINE',
        area='PARSE',
        template='Blank line {line} is not a valid JSONL document.',
        slots=(
            SlotSpec('line', SlotType.INT),
        ),
    ),
    'STRICTSPEC_PARSE_JSONL_DUPLICATE_KEY': Entry(
        code='STRICTSPEC_PARSE_JSONL_DUPLICATE_KEY',
        area='PARSE',
        template='Duplicate key {key} on JSONL line {line} at {path}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('line', SlotType.INT),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_PARSE_JSONL_LINE_SYNTAX': Entry(
        code='STRICTSPEC_PARSE_JSONL_LINE_SYNTAX',
        area='PARSE',
        template='JSONL parse error on line {line} at {path}: {detail}.',
        slots=(
            SlotSpec('line', SlotType.INT),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('detail', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_PARSE_JSONL_TRAILING_CR': Entry(
        code='STRICTSPEC_PARSE_JSONL_TRAILING_CR',
        area='PARSE',
        template='Line {line} ends with a carriage return; JSONL is LF-only.',
        slots=(
            SlotSpec('line', SlotType.INT),
        ),
    ),
    'STRICTSPEC_PARSE_JSON_DUPLICATE_KEY': Entry(
        code='STRICTSPEC_PARSE_JSON_DUPLICATE_KEY',
        area='PARSE',
        template='Duplicate key {key} in JSON object at {path}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_PARSE_JSON_EMPTY': Entry(
        code='STRICTSPEC_PARSE_JSON_EMPTY',
        area='PARSE',
        template='Empty input: expected a JSON document, found none.',
        slots=(),
    ),
    'STRICTSPEC_PARSE_JSON_SYNTAX': Entry(
        code='STRICTSPEC_PARSE_JSON_SYNTAX',
        area='PARSE',
        template='JSON parse error at {path}: {detail}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('detail', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_PARSE_JSON_TRAILING': Entry(
        code='STRICTSPEC_PARSE_JSON_TRAILING',
        area='PARSE',
        template='Trailing content after the JSON document at {path}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_PARSE_TOML_DUPLICATE_KEY': Entry(
        code='STRICTSPEC_PARSE_TOML_DUPLICATE_KEY',
        area='PARSE',
        template='Duplicate key {key} in TOML table at {path}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_PARSE_TOML_EMPTY': Entry(
        code='STRICTSPEC_PARSE_TOML_EMPTY',
        area='PARSE',
        template='Empty TOML input: expected a document, found none.',
        slots=(),
    ),
    'STRICTSPEC_PARSE_TOML_SYNTAX': Entry(
        code='STRICTSPEC_PARSE_TOML_SYNTAX',
        area='PARSE',
        template='TOML parse error at {path}: {detail}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('detail', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_SCALAR_BASE_MISMATCH': Entry(
        code='STRICTSPEC_SCALAR_BASE_MISMATCH',
        area='SCALAR',
        template='Value at {path} is not a {expected} lexeme, which the {name} scalar refines.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.STRING),
            SlotSpec('name', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_SCALAR_LENGTH': Entry(
        code='STRICTSPEC_SCALAR_LENGTH',
        area='SCALAR',
        template="Value at {path} violates the {name} scalar's length bound ({actual}, limit {limit}).",
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('name', SlotType.IDENTIFIER),
            SlotSpec('actual', SlotType.INT),
            SlotSpec('limit', SlotType.INT),
        ),
    ),
    'STRICTSPEC_SCALAR_LEXEME': Entry(
        code='STRICTSPEC_SCALAR_LEXEME',
        area='SCALAR',
        template="Value {actual} at {path} does not match the {name} scalar's lexeme rule {pattern}.",
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('name', SlotType.IDENTIFIER),
            SlotSpec('pattern', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_SCALAR_NO_BINDING': Entry(
        code='STRICTSPEC_SCALAR_NO_BINDING',
        area='SCALAR',
        template='Custom scalar {name} declares no binding for target {got}; every declared target requires a binding.',
        slots=(
            SlotSpec('name', SlotType.IDENTIFIER),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_SCALAR_UNKNOWN': Entry(
        code='STRICTSPEC_SCALAR_UNKNOWN',
        area='SCALAR',
        template='Field {path} uses custom scalar {name}, which is not registered in the manifest.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('name', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_SCHEMA_ALIAS_ON_DISCRIMINATOR': Entry(
        code='STRICTSPEC_SCHEMA_ALIAS_ON_DISCRIMINATOR',
        area='SCHEMA',
        template='Alias {alias} targets discriminator field {path}; a discriminator may not be aliased.',
        slots=(
            SlotSpec('alias', SlotType.IDENTIFIER),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_SCHEMA_DATETIME_KIND_MISMATCH': Entry(
        code='STRICTSPEC_SCHEMA_DATETIME_KIND_MISMATCH',
        area='SCHEMA',
        template='Datetime range at {path} compares an offset scalar with a local scalar; comparisons must be same-kind.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_SCHEMA_DEFAULT_KEY': Entry(
        code='STRICTSPEC_SCHEMA_DEFAULT_KEY',
        area='SCHEMA',
        template='The `default` key is not a construct of strictspec (field {path}); remove it. A typed value never carries data the author did not write.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_SCHEMA_MISSING_FORMAT_VERSION': Entry(
        code='STRICTSPEC_SCHEMA_MISSING_FORMAT_VERSION',
        area='SCHEMA',
        template='Schema {schema} does not declare `format_version`.',
        slots=(
            SlotSpec('schema', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_SCHEMA_MISSING_META_VERSION': Entry(
        code='STRICTSPEC_SCHEMA_MISSING_META_VERSION',
        area='SCHEMA',
        template='Schema {schema} does not declare `meta_version`.',
        slots=(
            SlotSpec('schema', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_SCHEMA_NODE_KIND_UNION_AMBIGUOUS': Entry(
        code='STRICTSPEC_SCHEMA_NODE_KIND_UNION_AMBIGUOUS',
        area='SCHEMA',
        template='Undiscriminated union at {path} has two arms of the same node kind ({kind}); same-kind arms require a discriminator.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('kind', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_SCHEMA_OPAQUE_NO_STANCE': Entry(
        code='STRICTSPEC_SCHEMA_OPAQUE_NO_STANCE',
        area='SCHEMA',
        template='Opaque JSON leaf {path} declares neither `consumer_check` nor `unchecked`; one is required.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_SCHEMA_REGEX_UNSUPPORTED': Entry(
        code='STRICTSPEC_SCHEMA_REGEX_UNSUPPORTED',
        area='SCHEMA',
        template='Regex at {path} uses a feature outside the RE2-compatible subset: {detail}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('detail', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_SCHEMA_TOML_NULLABLE': Entry(
        code='STRICTSPEC_SCHEMA_TOML_NULLABLE',
        area='SCHEMA',
        template='A nullable union is reachable at {path}, but the target document syntax is TOML; TOML models absence as an optional field.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_SCHEMA_TS_WITHOUT_SAFE_INTEGERS': Entry(
        code='STRICTSPEC_SCHEMA_TS_WITHOUT_SAFE_INTEGERS',
        area='SCHEMA',
        template='Schema {schema} declares a TypeScript target but omits `safe_integers = true`; a TS target requires it.',
        slots=(
            SlotSpec('schema', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_SCHEMA_TUPLE_ARRAY_BOUNDS': Entry(
        code='STRICTSPEC_SCHEMA_TUPLE_ARRAY_BOUNDS',
        area='SCHEMA',
        template='Field {path} declares both tuple form and array-length bounds; the two are mutually exclusive.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_SCHEMA_UNCHECKED_NO_REASON': Entry(
        code='STRICTSPEC_SCHEMA_UNCHECKED_NO_REASON',
        area='SCHEMA',
        template='Leaf {path} declares `unchecked = true` without the mandatory `unchecked_reason`.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_SCHEMA_UNKNOWN_META_KEY': Entry(
        code='STRICTSPEC_SCHEMA_UNKNOWN_META_KEY',
        area='SCHEMA',
        template='Unknown meta-schema key {key} at {path}.{suggestion}',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('suggestion', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_SCHEMA_UNKNOWN_TYPE_REF': Entry(
        code='STRICTSPEC_SCHEMA_UNKNOWN_TYPE_REF',
        area='SCHEMA',
        template='Field {path} references named type {name}, which is not declared or imported.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('name', SlotType.IDENTIFIER),
        ),
    ),
    'STRICTSPEC_SERIALIZE_NONCURRENT': Entry(
        code='STRICTSPEC_SERIALIZE_NONCURRENT',
        area='SERIALIZE',
        template='Refusing to serialize document at {path}: its `format_version` is {got}, but schema {schema} serializes only the current {expected}. Migrate before writing.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.VERSION),
            SlotSpec('schema', SlotType.IDENTIFIER),
            SlotSpec('expected', SlotType.VERSION),
        ),
    ),
    'STRICTSPEC_TYPE_DATETIME_KIND': Entry(
        code='STRICTSPEC_TYPE_DATETIME_KIND',
        area='TYPE',
        template='Expected a {expected} datetime at {path}; got a {got} datetime.',
        slots=(
            SlotSpec('expected', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_MISMATCH': Entry(
        code='STRICTSPEC_TYPE_MISMATCH',
        area='TYPE',
        template='Expected {expected} at {path}, got {got}.',
        slots=(
            SlotSpec('expected', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_MISSING_REQUIRED': Entry(
        code='STRICTSPEC_TYPE_MISSING_REQUIRED',
        area='TYPE',
        template='Missing required field {key} at {path}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_ARRAY': Entry(
        code='STRICTSPEC_TYPE_NOT_ARRAY',
        area='TYPE',
        template='Expected an array at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_BOOLEAN': Entry(
        code='STRICTSPEC_TYPE_NOT_BOOLEAN',
        area='TYPE',
        template='Expected a boolean at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_DATE': Entry(
        code='STRICTSPEC_TYPE_NOT_DATE',
        area='TYPE',
        template='Expected a date at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_DATETIME': Entry(
        code='STRICTSPEC_TYPE_NOT_DATETIME',
        area='TYPE',
        template='Expected a datetime at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_ENUM_MEMBER': Entry(
        code='STRICTSPEC_TYPE_NOT_ENUM_MEMBER',
        area='TYPE',
        template='Value {got} at {path} is not one of {expected}.{suggestion}',
        slots=(
            SlotSpec('got', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.LIST, SlotType.STRING),
            SlotSpec('suggestion', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_FLOAT': Entry(
        code='STRICTSPEC_TYPE_NOT_FLOAT',
        area='TYPE',
        template='Expected a float at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_INTEGER': Entry(
        code='STRICTSPEC_TYPE_NOT_INTEGER',
        area='TYPE',
        template='Expected an integer at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_LITERAL': Entry(
        code='STRICTSPEC_TYPE_NOT_LITERAL',
        area='TYPE',
        template='Expected the literal {expected} at {path}, got {got}.',
        slots=(
            SlotSpec('expected', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_MAP': Entry(
        code='STRICTSPEC_TYPE_NOT_MAP',
        area='TYPE',
        template='Expected a map at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_RECORD': Entry(
        code='STRICTSPEC_TYPE_NOT_RECORD',
        area='TYPE',
        template='Expected a record at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_STRING': Entry(
        code='STRICTSPEC_TYPE_NOT_STRING',
        area='TYPE',
        template='Expected a string at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_NOT_TIME': Entry(
        code='STRICTSPEC_TYPE_NOT_TIME',
        area='TYPE',
        template='Expected a time at {path}, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_TYPE_TUPLE_ARITY': Entry(
        code='STRICTSPEC_TYPE_TUPLE_ARITY',
        area='TYPE',
        template='Tuple at {path} expects {expected} elements, got {got}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.INT),
            SlotSpec('got', SlotType.INT),
        ),
    ),
    'STRICTSPEC_UNION_DISCRIMINATOR_MISSING': Entry(
        code='STRICTSPEC_UNION_DISCRIMINATOR_MISSING',
        area='UNION',
        template='Missing discriminator {key} at {path}; expected one of {expected}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.LIST, SlotType.STRING),
        ),
    ),
    'STRICTSPEC_UNION_DISCRIMINATOR_UNKNOWN': Entry(
        code='STRICTSPEC_UNION_DISCRIMINATOR_UNKNOWN',
        area='UNION',
        template='Discriminator {got} at {path} is not one of {expected}.{suggestion}',
        slots=(
            SlotSpec('got', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('expected', SlotType.LIST, SlotType.STRING),
            SlotSpec('suggestion', SlotType.STRING),
        ),
    ),
    'STRICTSPEC_UNION_NODE_KIND': Entry(
        code='STRICTSPEC_UNION_NODE_KIND',
        area='UNION',
        template='No union arm at {path} accepts a {got}; expected one of {expected}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('got', SlotType.STRING),
            SlotSpec('expected', SlotType.LIST, SlotType.STRING),
        ),
    ),
    'STRICTSPEC_VALUE_ARRAY_TOO_LONG': Entry(
        code='STRICTSPEC_VALUE_ARRAY_TOO_LONG',
        area='VALUE',
        template='Array at {path} has {actual} elements; maximum is {limit}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.INT),
            SlotSpec('limit', SlotType.INT),
        ),
    ),
    'STRICTSPEC_VALUE_ARRAY_TOO_SHORT': Entry(
        code='STRICTSPEC_VALUE_ARRAY_TOO_SHORT',
        area='VALUE',
        template='Array at {path} has {actual} elements; minimum is {limit}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.INT),
            SlotSpec('limit', SlotType.INT),
        ),
    ),
    'STRICTSPEC_VALUE_DATETIME_AFTER': Entry(
        code='STRICTSPEC_VALUE_DATETIME_AFTER',
        area='VALUE',
        template='Datetime {actual} at {path} is after the maximum {limit}.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('limit', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_VALUE_DATETIME_BEFORE': Entry(
        code='STRICTSPEC_VALUE_DATETIME_BEFORE',
        area='VALUE',
        template='Datetime {actual} at {path} is before the minimum {limit}.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('limit', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_VALUE_MAP_KEY_REGEX': Entry(
        code='STRICTSPEC_VALUE_MAP_KEY_REGEX',
        area='VALUE',
        template='Map key {key} at {path} does not match the required key pattern {pattern}.',
        slots=(
            SlotSpec('key', SlotType.STRING),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('pattern', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_VALUE_NUM_TOO_LARGE': Entry(
        code='STRICTSPEC_VALUE_NUM_TOO_LARGE',
        area='VALUE',
        template='Value {actual} at {path} is above the maximum {limit}.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('limit', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_VALUE_NUM_TOO_LARGE_EXCLUSIVE': Entry(
        code='STRICTSPEC_VALUE_NUM_TOO_LARGE_EXCLUSIVE',
        area='VALUE',
        template='Value {actual} at {path} must be less than {limit}.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('limit', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_VALUE_NUM_TOO_SMALL': Entry(
        code='STRICTSPEC_VALUE_NUM_TOO_SMALL',
        area='VALUE',
        template='Value {actual} at {path} is below the minimum {limit}.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('limit', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_VALUE_NUM_TOO_SMALL_EXCLUSIVE': Entry(
        code='STRICTSPEC_VALUE_NUM_TOO_SMALL_EXCLUSIVE',
        area='VALUE',
        template='Value {actual} at {path} must be greater than {limit}.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('limit', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_VALUE_STRING_EMPTY': Entry(
        code='STRICTSPEC_VALUE_STRING_EMPTY',
        area='VALUE',
        template='String at {path} is empty; a non-empty value is required.',
        slots=(
            SlotSpec('path', SlotType.PATH),
        ),
    ),
    'STRICTSPEC_VALUE_STRING_REGEX': Entry(
        code='STRICTSPEC_VALUE_STRING_REGEX',
        area='VALUE',
        template='String {actual} at {path} does not match the required pattern {pattern}.',
        slots=(
            SlotSpec('actual', SlotType.VALUE),
            SlotSpec('path', SlotType.PATH),
            SlotSpec('pattern', SlotType.VALUE),
        ),
    ),
    'STRICTSPEC_VALUE_STRING_TOO_LONG': Entry(
        code='STRICTSPEC_VALUE_STRING_TOO_LONG',
        area='VALUE',
        template='String at {path} has {actual} code points; maximum is {limit}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.INT),
            SlotSpec('limit', SlotType.INT),
        ),
    ),
    'STRICTSPEC_VALUE_STRING_TOO_SHORT': Entry(
        code='STRICTSPEC_VALUE_STRING_TOO_SHORT',
        area='VALUE',
        template='String at {path} has {actual} code points; minimum is {limit}.',
        slots=(
            SlotSpec('path', SlotType.PATH),
            SlotSpec('actual', SlotType.INT),
            SlotSpec('limit', SlotType.INT),
        ),
    ),
}
