// Code generated by tools/gencodes from spec/appendix-error-codes.md. DO NOT EDIT.

package codes

// Areas is the closed area set (appendix-error-codes.md section 3).
var Areas = []string{
	"ALIAS",
	"CHANNEL",
	"CROSS",
	"DEPTH",
	"DIFF",
	"DOCDIFF",
	"ENUMSRC",
	"GATE",
	"IMPORT",
	"INTRA",
	"KEY",
	"MANIFEST",
	"METAGATE",
	"MIGRATE",
	"NUM",
	"PARSE",
	"SCALAR",
	"SCHEMA",
	"SERIALIZE",
	"TYPE",
	"UNION",
	"VALUE",
}

var catalogue = map[string]Entry{
	"STRICTSPEC_ALIAS_BOTH_PRESENT": {
		Code:     "STRICTSPEC_ALIAS_BOTH_PRESENT",
		Area:     "ALIAS",
		Template: "Both {alias} and canonical {canonical} are present at {path}; provide exactly one.",
		Slots: []SlotSpec{
			{Name: "alias", Type: SlotTypeIdentifier},
			{Name: "canonical", Type: SlotTypeIdentifier},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_CHANNEL_VERSION_REFUSED": {
		Code:     "STRICTSPEC_CHANNEL_VERSION_REFUSED",
		Area:     "CHANNEL",
		Template: "Cannot open channel for schema {schema}: peer offers `format_version` {got}, this endpoint speaks only {expected}. Update the client to the paired strictspec release ({release}).",
		Slots: []SlotSpec{
			{Name: "schema", Type: SlotTypeIdentifier},
			{Name: "got", Type: SlotTypeVersion},
			{Name: "expected", Type: SlotTypeVersion},
			{Name: "release", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_CROSS_COLLECTION_UNIQUE": {
		Code:     "STRICTSPEC_CROSS_COLLECTION_UNIQUE",
		Area:     "CROSS",
		Template: "Value {value} at {path} also appears in {source}; it must be unique across the collection family.",
		Slots: []SlotSpec{
			{Name: "value", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "source", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_CROSS_COUNT_LIMIT": {
		Code:     "STRICTSPEC_CROSS_COUNT_LIMIT",
		Area:     "CROSS",
		Template: "Collection at {path} has {actual} elements across {source}; the limit is {limit}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeInt},
			{Name: "source", Type: SlotTypeString},
			{Name: "limit", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_CROSS_REFERENCE_UNRESOLVED": {
		Code:     "STRICTSPEC_CROSS_REFERENCE_UNRESOLVED",
		Area:     "CROSS",
		Template: "Reference {value} at {path} does not resolve in {source}.",
		Slots: []SlotSpec{
			{Name: "value", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "source", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_CROSS_RESOLVER_UNAVAILABLE": {
		Code:     "STRICTSPEC_CROSS_RESOLVER_UNAVAILABLE",
		Area:     "CROSS",
		Template: "Constraint at {path} requires evidence resolver {source}, which this environment cannot satisfy.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "source", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_CROSS_SET_COVERAGE": {
		Code:     "STRICTSPEC_CROSS_SET_COVERAGE",
		Area:     "CROSS",
		Template: "Element {value} of {source} is not covered by the collection at {path}.",
		Slots: []SlotSpec{
			{Name: "value", Type: SlotTypeValue},
			{Name: "source", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_CROSS_SUM_FIELD_MISSING": {
		Code:     "STRICTSPEC_CROSS_SUM_FIELD_MISSING",
		Area:     "CROSS",
		Template: "sum-limit at {path} over {source} requires numeric field {field} on every selected document; document {actual} lacks it or has a non-numeric value.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "source", Type: SlotTypeString},
			{Name: "field", Type: SlotTypeString},
			{Name: "actual", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_CROSS_SUM_LIMIT": {
		Code:     "STRICTSPEC_CROSS_SUM_LIMIT",
		Area:     "CROSS",
		Template: "Sum of {field} across {source} at {path} is {actual}; the limit is {limit}.",
		Slots: []SlotSpec{
			{Name: "field", Type: SlotTypeString},
			{Name: "source", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeValue},
			{Name: "limit", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_DEPTH_EXCEEDED": {
		Code:     "STRICTSPEC_DEPTH_EXCEEDED",
		Area:     "DEPTH",
		Template: "Document nesting at {path} exceeds the maximum validation depth of {limit}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "limit", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_DIFF_ADJUDICATION_INVALID": {
		Code:     "STRICTSPEC_DIFF_ADJUDICATION_INVALID",
		Area:     "DIFF",
		Template: "Adjudication file {source} does not validate against the adjudication schema: {detail}.",
		Slots: []SlotSpec{
			{Name: "source", Type: SlotTypeString},
			{Name: "detail", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_DIFF_ADJUDICATION_MISSING": {
		Code:     "STRICTSPEC_DIFF_ADJUDICATION_MISSING",
		Area:     "DIFF",
		Template: "Claim {condition} is corpus-supported without a corpus, and no adjudication entry covers it.",
		Slots: []SlotSpec{
			{Name: "condition", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_DIFF_CORPUS_EMPTY": {
		Code:     "STRICTSPEC_DIFF_CORPUS_EMPTY",
		Area:     "DIFF",
		Template: "The corpus glob {source} resolved to zero documents; `diff` requires a non-empty corpus.",
		Slots: []SlotSpec{
			{Name: "source", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_DIFF_NARROWING_UNBUMPED": {
		Code:     "STRICTSPEC_DIFF_NARROWING_UNBUMPED",
		Area:     "DIFF",
		Template: "Document {source} is valid under the old schema but invalid under the new schema at the same `format_version` {expected}; this narrowing requires a version bump.",
		Slots: []SlotSpec{
			{Name: "source", Type: SlotTypeString},
			{Name: "expected", Type: SlotTypeVersion},
		},
	},
	"STRICTSPEC_DIFF_TAXONOMY_MISDECLARED": {
		Code:     "STRICTSPEC_DIFF_TAXONOMY_MISDECLARED",
		Area:     "DIFF",
		Template: "Op {op} is declared {expected} but the corpus shows it is {actual}.",
		Slots: []SlotSpec{
			{Name: "op", Type: SlotTypeString},
			{Name: "expected", Type: SlotTypeString},
			{Name: "actual", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_DIFF_VIOLATED": {
		Code:     "STRICTSPEC_DIFF_VIOLATED",
		Area:     "DIFF",
		Template: "Claim {condition} is VIOLATED: corpus document {source} is a counterexample.",
		Slots: []SlotSpec{
			{Name: "condition", Type: SlotTypeString},
			{Name: "source", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_DOCDIFF_INVALID_OPERAND": {
		Code:     "STRICTSPEC_DOCDIFF_INVALID_OPERAND",
		Area:     "DOCDIFF",
		Template: "Operand {source} does not validate against the schema; `doc-diff` compares valid documents.",
		Slots: []SlotSpec{
			{Name: "source", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_DOCDIFF_SCHEMA_MISMATCH": {
		Code:     "STRICTSPEC_DOCDIFF_SCHEMA_MISMATCH",
		Area:     "DOCDIFF",
		Template: "Documents {source} and {actual} do not share `format_version`; `doc-diff` compares documents of one schema at one version.",
		Slots: []SlotSpec{
			{Name: "source", Type: SlotTypeString},
			{Name: "actual", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_ENUMSRC_BAD_SELECTOR": {
		Code:     "STRICTSPEC_ENUMSRC_BAD_SELECTOR",
		Area:     "ENUMSRC",
		Template: "Enum-source selector {selector} at {path} does not resolve within {source}.",
		Slots: []SlotSpec{
			{Name: "selector", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "source", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_ENUMSRC_MISSING_SOURCE": {
		Code:     "STRICTSPEC_ENUMSRC_MISSING_SOURCE",
		Area:     "ENUMSRC",
		Template: "Enum at {path} sources arms from {source}, which does not exist.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "source", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_ENUMSRC_SOURCE_NOT_STRINGS": {
		Code:     "STRICTSPEC_ENUMSRC_SOURCE_NOT_STRINGS",
		Area:     "ENUMSRC",
		Template: "Enum source {source} at {path} yields a non-string arm; sourced enum arms must be strings.",
		Slots: []SlotSpec{
			{Name: "source", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_ENUMSRC_STALE": {
		Code:     "STRICTSPEC_ENUMSRC_STALE",
		Area:     "ENUMSRC",
		Template: "Baked enum arms at {path} differ from source {source}; regenerate with `strictspec gen`. Baked: {baked}. Source: {actual}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "source", Type: SlotTypeString},
			{Name: "baked", Type: SlotTypeList, ElemType: SlotTypeString},
			{Name: "actual", Type: SlotTypeList, ElemType: SlotTypeString},
		},
	},
	"STRICTSPEC_GATE_ABSENT": {
		Code:     "STRICTSPEC_GATE_ABSENT",
		Area:     "GATE",
		Template: "Document is missing `format_version`. Schema {schema} expects {expected}. Run: {invocation}",
		Slots: []SlotSpec{
			{Name: "schema", Type: SlotTypeIdentifier},
			{Name: "expected", Type: SlotTypeVersion},
			{Name: "invocation", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_GATE_UNSUPPORTED": {
		Code:     "STRICTSPEC_GATE_UNSUPPORTED",
		Area:     "GATE",
		Template: "Document `format_version` is {got}, but schema {schema} accepts exactly {expected} (migration set {migset}). Run: {invocation}",
		Slots: []SlotSpec{
			{Name: "got", Type: SlotTypeVersion},
			{Name: "schema", Type: SlotTypeIdentifier},
			{Name: "expected", Type: SlotTypeVersion},
			{Name: "migset", Type: SlotTypeIdentifier},
			{Name: "invocation", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_GATE_WRONG_TYPE": {
		Code:     "STRICTSPEC_GATE_WRONG_TYPE",
		Area:     "GATE",
		Template: "Document `format_version` must be an integer; got {got}. Schema {schema} expects {expected}. Run: {invocation}",
		Slots: []SlotSpec{
			{Name: "got", Type: SlotTypeValue},
			{Name: "schema", Type: SlotTypeIdentifier},
			{Name: "expected", Type: SlotTypeVersion},
			{Name: "invocation", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_IMPORT_CROSS_FILE_CONSTRAINT": {
		Code:     "STRICTSPEC_IMPORT_CROSS_FILE_CONSTRAINT",
		Area:     "IMPORT",
		Template: "Imported file {file} declares a constraint; type-definition files may declare types only, not constraints.",
		Slots: []SlotSpec{
			{Name: "file", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_IMPORT_MISSING_TYPE_FILE": {
		Code:     "STRICTSPEC_IMPORT_MISSING_TYPE_FILE",
		Area:     "IMPORT",
		Template: "Type-definition file {file} imported by {schema} does not exist.",
		Slots: []SlotSpec{
			{Name: "file", Type: SlotTypeString},
			{Name: "schema", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_IMPORT_TRANSITIVE": {
		Code:     "STRICTSPEC_IMPORT_TRANSITIVE",
		Area:     "IMPORT",
		Template: "Type-definition file {file} imports another file; transitive imports are not permitted.",
		Slots: []SlotSpec{
			{Name: "file", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_IMPORT_UNKNOWN_TYPE": {
		Code:     "STRICTSPEC_IMPORT_UNKNOWN_TYPE",
		Area:     "IMPORT",
		Template: "Type {name} is not defined in imported file {file}.",
		Slots: []SlotSpec{
			{Name: "name", Type: SlotTypeIdentifier},
			{Name: "file", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_AT_LEAST_ONE_OF": {
		Code:     "STRICTSPEC_INTRA_AT_LEAST_ONE_OF",
		Area:     "INTRA",
		Template: "At least one of {fields} must be present at {path}; none were.",
		Slots: []SlotSpec{
			{Name: "fields", Type: SlotTypeList, ElemType: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_INTRA_COLLECTIONS_DISJOINT": {
		Code:     "STRICTSPEC_INTRA_COLLECTIONS_DISJOINT",
		Area:     "INTRA",
		Template: "Arrays {fields} at {path} must share no element; {value} appears in both (normalization: {normalization}).",
		Slots: []SlotSpec{
			{Name: "fields", Type: SlotTypeList, ElemType: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "value", Type: SlotTypeValue},
			{Name: "normalization", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_CONDITIONAL_REQUIRED": {
		Code:     "STRICTSPEC_INTRA_CONDITIONAL_REQUIRED",
		Area:     "INTRA",
		Template: "Field {key} at {path} is required when {condition}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "condition", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_CONDITIONAL_VALUE": {
		Code:     "STRICTSPEC_INTRA_CONDITIONAL_VALUE",
		Area:     "INTRA",
		Template: "Field {key} at {path} must equal {expected} when {condition}; got {got}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeValue},
			{Name: "condition", Type: SlotTypeString},
			{Name: "got", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_INTRA_CO_PRESENCE": {
		Code:     "STRICTSPEC_INTRA_CO_PRESENCE",
		Area:     "INTRA",
		Template: "Fields {fields} at {path} must be present together or absent together; found {actual}.",
		Slots: []SlotSpec{
			{Name: "fields", Type: SlotTypeList, ElemType: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeList, ElemType: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_EXACTLY_ONE_OF": {
		Code:     "STRICTSPEC_INTRA_EXACTLY_ONE_OF",
		Area:     "INTRA",
		Template: "Exactly one of {fields} must be present at {path}; found {actual}.",
		Slots: []SlotSpec{
			{Name: "fields", Type: SlotTypeList, ElemType: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeList, ElemType: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_FORBIDDEN_WHEN": {
		Code:     "STRICTSPEC_INTRA_FORBIDDEN_WHEN",
		Area:     "INTRA",
		Template: "Field {key} at {path} is forbidden when {condition}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "condition", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_MUTUAL_EXCLUSION": {
		Code:     "STRICTSPEC_INTRA_MUTUAL_EXCLUSION",
		Area:     "INTRA",
		Template: "Fields {fields} at {path} are mutually exclusive; found {actual}.",
		Slots: []SlotSpec{
			{Name: "fields", Type: SlotTypeList, ElemType: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeList, ElemType: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_ORDERED_PAIR": {
		Code:     "STRICTSPEC_INTRA_ORDERED_PAIR",
		Area:     "INTRA",
		Template: "Field {actual} at {path} must be less than sibling {value}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "value", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_PAIRWISE_DISTINCT": {
		Code:     "STRICTSPEC_INTRA_PAIRWISE_DISTINCT",
		Area:     "INTRA",
		Template: "Values at {path} must be pairwise distinct; {value} repeats (normalization: {normalization}).",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "value", Type: SlotTypeValue},
			{Name: "normalization", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_INTRA_RANGES_DISJOINT": {
		Code:     "STRICTSPEC_INTRA_RANGES_DISJOINT",
		Area:     "INTRA",
		Template: "Half-open ranges at {path} overlap: {value} intersects {actual}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "value", Type: SlotTypeValue},
			{Name: "actual", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_INTRA_REFERENCE_UNRESOLVED": {
		Code:     "STRICTSPEC_INTRA_REFERENCE_UNRESOLVED",
		Area:     "INTRA",
		Template: "Reference {value} at {path} does not resolve within the document.",
		Slots: []SlotSpec{
			{Name: "value", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_INTRA_UNIQUE_BY": {
		Code:     "STRICTSPEC_INTRA_UNIQUE_BY",
		Area:     "INTRA",
		Template: "Duplicate value {value} for unique-by {field} at {path} (normalization: {normalization}).",
		Slots: []SlotSpec{
			{Name: "value", Type: SlotTypeValue},
			{Name: "field", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "normalization", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_KEY_DUPLICATE": {
		Code:     "STRICTSPEC_KEY_DUPLICATE",
		Area:     "KEY",
		Template: "Duplicate key {key} at {path}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_KEY_UNKNOWN": {
		Code:     "STRICTSPEC_KEY_UNKNOWN",
		Area:     "KEY",
		Template: "Unknown key {key} at {path}.{suggestion}",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "suggestion", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_MANIFEST_ALREADY_EXISTS": {
		Code:     "STRICTSPEC_MANIFEST_ALREADY_EXISTS",
		Area:     "MANIFEST",
		Template: "A `strictspec.toml` already exists at {path}; `strictspec init` refuses to overwrite it.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_MANIFEST_DRIFT": {
		Code:     "STRICTSPEC_MANIFEST_DRIFT",
		Area:     "MANIFEST",
		Template: "Generated output at {path} differs from a fresh generation; run `strictspec gen` and commit.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_MANIFEST_GENERATED_PATH_DIRTY": {
		Code:     "STRICTSPEC_MANIFEST_GENERATED_PATH_DIRTY",
		Area:     "MANIFEST",
		Template: "Generated path {path} has uncommitted local edits; regenerate before proceeding.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_MANIFEST_PAIRING_MISMATCH": {
		Code:     "STRICTSPEC_MANIFEST_PAIRING_MISMATCH",
		Area:     "MANIFEST",
		Template: "Runtime version {actual} does not match generated-code version {expected}; regenerate against the paired release.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeVersion},
			{Name: "expected", Type: SlotTypeVersion},
		},
	},
	"STRICTSPEC_MANIFEST_UNKNOWN_RESOLVER": {
		Code:     "STRICTSPEC_MANIFEST_UNKNOWN_RESOLVER",
		Area:     "MANIFEST",
		Template: "Manifest / schema references evidence resolver {name}, which is not in the resolver vocabulary.",
		Slots: []SlotSpec{
			{Name: "name", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_MANIFEST_UNKNOWN_STORE": {
		Code:     "STRICTSPEC_MANIFEST_UNKNOWN_STORE",
		Area:     "MANIFEST",
		Template: "Manifest declares store {name}, whose kind {got} is not a recognized store kind.",
		Slots: []SlotSpec{
			{Name: "name", Type: SlotTypeIdentifier},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_METAGATE_ABSENT": {
		Code:     "STRICTSPEC_METAGATE_ABSENT",
		Area:     "METAGATE",
		Template: "Schema {schema} is missing `meta_version`. This strictspec release expects {expected}. Run: {invocation}",
		Slots: []SlotSpec{
			{Name: "schema", Type: SlotTypeIdentifier},
			{Name: "expected", Type: SlotTypeVersion},
			{Name: "invocation", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_METAGATE_UNSUPPORTED": {
		Code:     "STRICTSPEC_METAGATE_UNSUPPORTED",
		Area:     "METAGATE",
		Template: "Schema {schema} declares `meta_version` {got}, but this strictspec release supports {expected}. Run: {invocation}",
		Slots: []SlotSpec{
			{Name: "schema", Type: SlotTypeIdentifier},
			{Name: "got", Type: SlotTypeVersion},
			{Name: "expected", Type: SlotTypeVersion},
			{Name: "invocation", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_METAGATE_WRONG_TYPE": {
		Code:     "STRICTSPEC_METAGATE_WRONG_TYPE",
		Area:     "METAGATE",
		Template: "Schema `meta_version` must be an integer; got {got}.",
		Slots: []SlotSpec{
			{Name: "got", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_MIGRATE_COLLISION": {
		Code:     "STRICTSPEC_MIGRATE_COLLISION",
		Area:     "MIGRATE",
		Template: "Migration op {op} would write {path}, which already exists.",
		Slots: []SlotSpec{
			{Name: "op", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_MIGRATE_IRREVERSIBLE_DOWN": {
		Code:     "STRICTSPEC_MIGRATE_IRREVERSIBLE_DOWN",
		Area:     "MIGRATE",
		Template: "Op {op} at {path} is declared irreversible; a down-migration was requested.",
		Slots: []SlotSpec{
			{Name: "op", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_MIGRATE_ON_CURRENT": {
		Code:     "STRICTSPEC_MIGRATE_ON_CURRENT",
		Area:     "MIGRATE",
		Template: "Document at {path} is already at the current `format_version` {expected}; nothing to migrate.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeVersion},
		},
	},
	"STRICTSPEC_MIGRATE_PREDICATE_UNSUPPORTED": {
		Code:     "STRICTSPEC_MIGRATE_PREDICATE_UNSUPPORTED",
		Area:     "MIGRATE",
		Template: "Predicate at {path} tests more than equality and presence; migration predicates are restricted.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_MIGRATE_REVALIDATION_FAILED": {
		Code:     "STRICTSPEC_MIGRATE_REVALIDATION_FAILED",
		Area:     "MIGRATE",
		Template: "Migrated document at {path} does not validate at `format_version` {expected}; the migration is unsound.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeVersion},
		},
	},
	"STRICTSPEC_MIGRATE_TARGET_MISSING": {
		Code:     "STRICTSPEC_MIGRATE_TARGET_MISSING",
		Area:     "MIGRATE",
		Template: "Migration op {op} targets {path}, which is absent in the document.",
		Slots: []SlotSpec{
			{Name: "op", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_MIGRATE_TYPE_MISMATCH": {
		Code:     "STRICTSPEC_MIGRATE_TYPE_MISMATCH",
		Area:     "MIGRATE",
		Template: "Migration op {op} at {path} expected {expected}, found {got}.",
		Slots: []SlotSpec{
			{Name: "op", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeString},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_MIGRATE_UNKNOWN_SET": {
		Code:     "STRICTSPEC_MIGRATE_UNKNOWN_SET",
		Area:     "MIGRATE",
		Template: "No migration set {migset} is registered for schema {schema}.",
		Slots: []SlotSpec{
			{Name: "migset", Type: SlotTypeIdentifier},
			{Name: "schema", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_MIGRATE_UNWRAP_NOT_SINGLETON": {
		Code:     "STRICTSPEC_MIGRATE_UNWRAP_NOT_SINGLETON",
		Area:     "MIGRATE",
		Template: "unwrap_singleton at {path} requires a single-element array; found {actual} elements.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_NUM_FLOAT_OVERFLOW": {
		Code:     "STRICTSPEC_NUM_FLOAT_OVERFLOW",
		Area:     "NUM",
		Template: "Float lexeme {actual} at {path} is beyond float64 range.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_NUM_INT_OVERFLOW": {
		Code:     "STRICTSPEC_NUM_INT_OVERFLOW",
		Area:     "NUM",
		Template: "Integer lexeme {actual} at {path} overflows int64.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_NUM_NON_FINITE": {
		Code:     "STRICTSPEC_NUM_NON_FINITE",
		Area:     "NUM",
		Template: "Non-finite number {actual} at {path} is not permitted.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_NUM_SAFE_INTEGER": {
		Code:     "STRICTSPEC_NUM_SAFE_INTEGER",
		Area:     "NUM",
		Template: "Integer {actual} at {path} exceeds the safe-integer range (|n| >= 2^53) required by `safe_integers`.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_NUM_UNREPRESENTABLE": {
		Code:     "STRICTSPEC_NUM_UNREPRESENTABLE",
		Area:     "NUM",
		Template: "Lexeme {actual} at {path} cannot be represented exactly as float64; the `number` scalar refuses silent precision loss.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_PARSE_JSONL_BLANK_LINE": {
		Code:     "STRICTSPEC_PARSE_JSONL_BLANK_LINE",
		Area:     "PARSE",
		Template: "Blank line {line} is not a valid JSONL document.",
		Slots: []SlotSpec{
			{Name: "line", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_PARSE_JSONL_DUPLICATE_KEY": {
		Code:     "STRICTSPEC_PARSE_JSONL_DUPLICATE_KEY",
		Area:     "PARSE",
		Template: "Duplicate key {key} on JSONL line {line} at {path}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "line", Type: SlotTypeInt},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_PARSE_JSONL_LINE_SYNTAX": {
		Code:     "STRICTSPEC_PARSE_JSONL_LINE_SYNTAX",
		Area:     "PARSE",
		Template: "JSONL parse error on line {line} at {path}: {detail}.",
		Slots: []SlotSpec{
			{Name: "line", Type: SlotTypeInt},
			{Name: "path", Type: SlotTypePath},
			{Name: "detail", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_PARSE_JSONL_TRAILING_CR": {
		Code:     "STRICTSPEC_PARSE_JSONL_TRAILING_CR",
		Area:     "PARSE",
		Template: "Line {line} ends with a carriage return; JSONL is LF-only.",
		Slots: []SlotSpec{
			{Name: "line", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_PARSE_JSON_DUPLICATE_KEY": {
		Code:     "STRICTSPEC_PARSE_JSON_DUPLICATE_KEY",
		Area:     "PARSE",
		Template: "Duplicate key {key} in JSON object at {path}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_PARSE_JSON_EMPTY": {
		Code:     "STRICTSPEC_PARSE_JSON_EMPTY",
		Area:     "PARSE",
		Template: "Empty input: expected a JSON document, found none.",
		Slots:    nil,
	},
	"STRICTSPEC_PARSE_JSON_SYNTAX": {
		Code:     "STRICTSPEC_PARSE_JSON_SYNTAX",
		Area:     "PARSE",
		Template: "JSON parse error at {path}: {detail}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "detail", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_PARSE_JSON_TRAILING": {
		Code:     "STRICTSPEC_PARSE_JSON_TRAILING",
		Area:     "PARSE",
		Template: "Trailing content after the JSON document at {path}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_PARSE_TOML_DUPLICATE_KEY": {
		Code:     "STRICTSPEC_PARSE_TOML_DUPLICATE_KEY",
		Area:     "PARSE",
		Template: "Duplicate key {key} in TOML table at {path}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_PARSE_TOML_EMPTY": {
		Code:     "STRICTSPEC_PARSE_TOML_EMPTY",
		Area:     "PARSE",
		Template: "Empty TOML input: expected a document, found none.",
		Slots:    nil,
	},
	"STRICTSPEC_PARSE_TOML_SYNTAX": {
		Code:     "STRICTSPEC_PARSE_TOML_SYNTAX",
		Area:     "PARSE",
		Template: "TOML parse error at {path}: {detail}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "detail", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_SCALAR_BASE_MISMATCH": {
		Code:     "STRICTSPEC_SCALAR_BASE_MISMATCH",
		Area:     "SCALAR",
		Template: "Value at {path} is not a {expected} lexeme, which the {name} scalar refines.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeString},
			{Name: "name", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_SCALAR_LENGTH": {
		Code:     "STRICTSPEC_SCALAR_LENGTH",
		Area:     "SCALAR",
		Template: "Value at {path} violates the {name} scalar's length bound ({actual}, limit {limit}).",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "name", Type: SlotTypeIdentifier},
			{Name: "actual", Type: SlotTypeInt},
			{Name: "limit", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_SCALAR_LEXEME": {
		Code:     "STRICTSPEC_SCALAR_LEXEME",
		Area:     "SCALAR",
		Template: "Value {actual} at {path} does not match the {name} scalar's lexeme rule {pattern}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "name", Type: SlotTypeIdentifier},
			{Name: "pattern", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_SCALAR_NO_BINDING": {
		Code:     "STRICTSPEC_SCALAR_NO_BINDING",
		Area:     "SCALAR",
		Template: "Custom scalar {name} declares no binding for target {got}; every declared target requires a binding.",
		Slots: []SlotSpec{
			{Name: "name", Type: SlotTypeIdentifier},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_SCALAR_UNKNOWN": {
		Code:     "STRICTSPEC_SCALAR_UNKNOWN",
		Area:     "SCALAR",
		Template: "Field {path} uses custom scalar {name}, which is not registered in the manifest.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "name", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_SCHEMA_ALIAS_ON_DISCRIMINATOR": {
		Code:     "STRICTSPEC_SCHEMA_ALIAS_ON_DISCRIMINATOR",
		Area:     "SCHEMA",
		Template: "Alias {alias} targets discriminator field {path}; a discriminator may not be aliased.",
		Slots: []SlotSpec{
			{Name: "alias", Type: SlotTypeIdentifier},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_SCHEMA_DATETIME_KIND_MISMATCH": {
		Code:     "STRICTSPEC_SCHEMA_DATETIME_KIND_MISMATCH",
		Area:     "SCHEMA",
		Template: "Datetime range at {path} compares an offset scalar with a local scalar; comparisons must be same-kind.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_SCHEMA_DEFAULT_KEY": {
		Code:     "STRICTSPEC_SCHEMA_DEFAULT_KEY",
		Area:     "SCHEMA",
		Template: "The `default` key is not a construct of strictspec (field {path}); remove it. A typed value never carries data the author did not write.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_SCHEMA_MISSING_FORMAT_VERSION": {
		Code:     "STRICTSPEC_SCHEMA_MISSING_FORMAT_VERSION",
		Area:     "SCHEMA",
		Template: "Schema {schema} does not declare `format_version`.",
		Slots: []SlotSpec{
			{Name: "schema", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_SCHEMA_MISSING_META_VERSION": {
		Code:     "STRICTSPEC_SCHEMA_MISSING_META_VERSION",
		Area:     "SCHEMA",
		Template: "Schema {schema} does not declare `meta_version`.",
		Slots: []SlotSpec{
			{Name: "schema", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_SCHEMA_NODE_KIND_UNION_AMBIGUOUS": {
		Code:     "STRICTSPEC_SCHEMA_NODE_KIND_UNION_AMBIGUOUS",
		Area:     "SCHEMA",
		Template: "Undiscriminated union at {path} has two arms of the same node kind ({kind}); same-kind arms require a discriminator.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "kind", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_SCHEMA_OPAQUE_NO_STANCE": {
		Code:     "STRICTSPEC_SCHEMA_OPAQUE_NO_STANCE",
		Area:     "SCHEMA",
		Template: "Opaque JSON leaf {path} declares neither `consumer_check` nor `unchecked`; one is required.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_SCHEMA_REGEX_UNSUPPORTED": {
		Code:     "STRICTSPEC_SCHEMA_REGEX_UNSUPPORTED",
		Area:     "SCHEMA",
		Template: "Regex at {path} uses a feature outside the RE2-compatible subset: {detail}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "detail", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_SCHEMA_TOML_NULLABLE": {
		Code:     "STRICTSPEC_SCHEMA_TOML_NULLABLE",
		Area:     "SCHEMA",
		Template: "A nullable union is reachable at {path}, but the target document syntax is TOML; TOML models absence as an optional field.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_SCHEMA_TS_WITHOUT_SAFE_INTEGERS": {
		Code:     "STRICTSPEC_SCHEMA_TS_WITHOUT_SAFE_INTEGERS",
		Area:     "SCHEMA",
		Template: "Schema {schema} declares a TypeScript target but omits `safe_integers = true`; a TS target requires it.",
		Slots: []SlotSpec{
			{Name: "schema", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_SCHEMA_TUPLE_ARRAY_BOUNDS": {
		Code:     "STRICTSPEC_SCHEMA_TUPLE_ARRAY_BOUNDS",
		Area:     "SCHEMA",
		Template: "Field {path} declares both tuple form and array-length bounds; the two are mutually exclusive.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_SCHEMA_UNCHECKED_NO_REASON": {
		Code:     "STRICTSPEC_SCHEMA_UNCHECKED_NO_REASON",
		Area:     "SCHEMA",
		Template: "Leaf {path} declares `unchecked = true` without the mandatory `unchecked_reason`.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_SCHEMA_UNKNOWN_META_KEY": {
		Code:     "STRICTSPEC_SCHEMA_UNKNOWN_META_KEY",
		Area:     "SCHEMA",
		Template: "Unknown meta-schema key {key} at {path}.{suggestion}",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "suggestion", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_SCHEMA_UNKNOWN_TYPE_REF": {
		Code:     "STRICTSPEC_SCHEMA_UNKNOWN_TYPE_REF",
		Area:     "SCHEMA",
		Template: "Field {path} references named type {name}, which is not declared or imported.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "name", Type: SlotTypeIdentifier},
		},
	},
	"STRICTSPEC_SERIALIZE_NONCURRENT": {
		Code:     "STRICTSPEC_SERIALIZE_NONCURRENT",
		Area:     "SERIALIZE",
		Template: "Refusing to serialize document at {path}: its `format_version` is {got}, but schema {schema} serializes only the current {expected}. Migrate before writing.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeVersion},
			{Name: "schema", Type: SlotTypeIdentifier},
			{Name: "expected", Type: SlotTypeVersion},
		},
	},
	"STRICTSPEC_TYPE_DATETIME_KIND": {
		Code:     "STRICTSPEC_TYPE_DATETIME_KIND",
		Area:     "TYPE",
		Template: "Expected a {expected} datetime at {path}; got a {got} datetime.",
		Slots: []SlotSpec{
			{Name: "expected", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_MISMATCH": {
		Code:     "STRICTSPEC_TYPE_MISMATCH",
		Area:     "TYPE",
		Template: "Expected {expected} at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "expected", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_MISSING_REQUIRED": {
		Code:     "STRICTSPEC_TYPE_MISSING_REQUIRED",
		Area:     "TYPE",
		Template: "Missing required field {key} at {path}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_TYPE_NOT_ARRAY": {
		Code:     "STRICTSPEC_TYPE_NOT_ARRAY",
		Area:     "TYPE",
		Template: "Expected an array at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_BOOLEAN": {
		Code:     "STRICTSPEC_TYPE_NOT_BOOLEAN",
		Area:     "TYPE",
		Template: "Expected a boolean at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_DATE": {
		Code:     "STRICTSPEC_TYPE_NOT_DATE",
		Area:     "TYPE",
		Template: "Expected a date at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_DATETIME": {
		Code:     "STRICTSPEC_TYPE_NOT_DATETIME",
		Area:     "TYPE",
		Template: "Expected a datetime at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_ENUM_MEMBER": {
		Code:     "STRICTSPEC_TYPE_NOT_ENUM_MEMBER",
		Area:     "TYPE",
		Template: "Value {got} at {path} is not one of {expected}.{suggestion}",
		Slots: []SlotSpec{
			{Name: "got", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeList, ElemType: SlotTypeString},
			{Name: "suggestion", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_FLOAT": {
		Code:     "STRICTSPEC_TYPE_NOT_FLOAT",
		Area:     "TYPE",
		Template: "Expected a float at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_INTEGER": {
		Code:     "STRICTSPEC_TYPE_NOT_INTEGER",
		Area:     "TYPE",
		Template: "Expected an integer at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_LITERAL": {
		Code:     "STRICTSPEC_TYPE_NOT_LITERAL",
		Area:     "TYPE",
		Template: "Expected the literal {expected} at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "expected", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_TYPE_NOT_MAP": {
		Code:     "STRICTSPEC_TYPE_NOT_MAP",
		Area:     "TYPE",
		Template: "Expected a map at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_RECORD": {
		Code:     "STRICTSPEC_TYPE_NOT_RECORD",
		Area:     "TYPE",
		Template: "Expected a record at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_STRING": {
		Code:     "STRICTSPEC_TYPE_NOT_STRING",
		Area:     "TYPE",
		Template: "Expected a string at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_NOT_TIME": {
		Code:     "STRICTSPEC_TYPE_NOT_TIME",
		Area:     "TYPE",
		Template: "Expected a time at {path}, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_TYPE_TUPLE_ARITY": {
		Code:     "STRICTSPEC_TYPE_TUPLE_ARITY",
		Area:     "TYPE",
		Template: "Tuple at {path} expects {expected} elements, got {got}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeInt},
			{Name: "got", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_UNION_DISCRIMINATOR_MISSING": {
		Code:     "STRICTSPEC_UNION_DISCRIMINATOR_MISSING",
		Area:     "UNION",
		Template: "Missing discriminator {key} at {path}; expected one of {expected}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeList, ElemType: SlotTypeString},
		},
	},
	"STRICTSPEC_UNION_DISCRIMINATOR_UNKNOWN": {
		Code:     "STRICTSPEC_UNION_DISCRIMINATOR_UNKNOWN",
		Area:     "UNION",
		Template: "Discriminator {got} at {path} is not one of {expected}.{suggestion}",
		Slots: []SlotSpec{
			{Name: "got", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "expected", Type: SlotTypeList, ElemType: SlotTypeString},
			{Name: "suggestion", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_UNION_NODE_KIND": {
		Code:     "STRICTSPEC_UNION_NODE_KIND",
		Area:     "UNION",
		Template: "No union arm at {path} accepts a {got}; expected one of {expected}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "got", Type: SlotTypeString},
			{Name: "expected", Type: SlotTypeList, ElemType: SlotTypeString},
		},
	},
	"STRICTSPEC_VALUE_ARRAY_TOO_LONG": {
		Code:     "STRICTSPEC_VALUE_ARRAY_TOO_LONG",
		Area:     "VALUE",
		Template: "Array at {path} has {actual} elements; maximum is {limit}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeInt},
			{Name: "limit", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_VALUE_ARRAY_TOO_SHORT": {
		Code:     "STRICTSPEC_VALUE_ARRAY_TOO_SHORT",
		Area:     "VALUE",
		Template: "Array at {path} has {actual} elements; minimum is {limit}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeInt},
			{Name: "limit", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_VALUE_DATETIME_AFTER": {
		Code:     "STRICTSPEC_VALUE_DATETIME_AFTER",
		Area:     "VALUE",
		Template: "Datetime {actual} at {path} is after the maximum {limit}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "limit", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_VALUE_DATETIME_BEFORE": {
		Code:     "STRICTSPEC_VALUE_DATETIME_BEFORE",
		Area:     "VALUE",
		Template: "Datetime {actual} at {path} is before the minimum {limit}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "limit", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_VALUE_MAP_KEY_REGEX": {
		Code:     "STRICTSPEC_VALUE_MAP_KEY_REGEX",
		Area:     "VALUE",
		Template: "Map key {key} at {path} does not match the required key pattern {pattern}.",
		Slots: []SlotSpec{
			{Name: "key", Type: SlotTypeString},
			{Name: "path", Type: SlotTypePath},
			{Name: "pattern", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_VALUE_NUM_TOO_LARGE": {
		Code:     "STRICTSPEC_VALUE_NUM_TOO_LARGE",
		Area:     "VALUE",
		Template: "Value {actual} at {path} is above the maximum {limit}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "limit", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_VALUE_NUM_TOO_LARGE_EXCLUSIVE": {
		Code:     "STRICTSPEC_VALUE_NUM_TOO_LARGE_EXCLUSIVE",
		Area:     "VALUE",
		Template: "Value {actual} at {path} must be less than {limit}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "limit", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_VALUE_NUM_TOO_SMALL": {
		Code:     "STRICTSPEC_VALUE_NUM_TOO_SMALL",
		Area:     "VALUE",
		Template: "Value {actual} at {path} is below the minimum {limit}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "limit", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_VALUE_NUM_TOO_SMALL_EXCLUSIVE": {
		Code:     "STRICTSPEC_VALUE_NUM_TOO_SMALL_EXCLUSIVE",
		Area:     "VALUE",
		Template: "Value {actual} at {path} must be greater than {limit}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "limit", Type: SlotTypeValue},
		},
	},
	"STRICTSPEC_VALUE_STRING_EMPTY": {
		Code:     "STRICTSPEC_VALUE_STRING_EMPTY",
		Area:     "VALUE",
		Template: "String at {path} is empty; a non-empty value is required.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
		},
	},
	"STRICTSPEC_VALUE_STRING_REGEX": {
		Code:     "STRICTSPEC_VALUE_STRING_REGEX",
		Area:     "VALUE",
		Template: "String {actual} at {path} does not match the required pattern {pattern}.",
		Slots: []SlotSpec{
			{Name: "actual", Type: SlotTypeValue},
			{Name: "path", Type: SlotTypePath},
			{Name: "pattern", Type: SlotTypeString},
		},
	},
	"STRICTSPEC_VALUE_STRING_TOO_LONG": {
		Code:     "STRICTSPEC_VALUE_STRING_TOO_LONG",
		Area:     "VALUE",
		Template: "String at {path} has {actual} code points; maximum is {limit}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeInt},
			{Name: "limit", Type: SlotTypeInt},
		},
	},
	"STRICTSPEC_VALUE_STRING_TOO_SHORT": {
		Code:     "STRICTSPEC_VALUE_STRING_TOO_SHORT",
		Area:     "VALUE",
		Template: "String at {path} has {actual} code points; minimum is {limit}.",
		Slots: []SlotSpec{
			{Name: "path", Type: SlotTypePath},
			{Name: "actual", Type: SlotTypeInt},
			{Name: "limit", Type: SlotTypeInt},
		},
	},
}
