// Package emit is the Go EMITTER: given a resolved schema (and the in-memory
// file set backing it — the schema, any imported type-definition files, and the
// scalar manifest), it produces the generated Go validator source per the
// Generated API Contract (spec/DESIGN.md):
//
//   - the pinned generated-file header (generator version, schema name +
//     format_version, regeneration command, generated-by + lint-suppression
//     markers, MIT/unencumbered notice);
//   - the version-pairing guard (init hard-errors unless the runtime it links
//     against is the exact release that generated the code);
//   - the compiled schema, embedded, driving the SHARED emitter IR — so a
//     generated validator runs the identical checks as the interpreter (byte
//     identity is structural, not coincidental);
//   - the two entry points: raw bytes and a tagged document value;
//   - immutable typed frozen structs per named record type, with generated
//     `With*` copy helpers (per-field copy-on-write).
//
// Messages are rendered by the runtime's catalogue-driven renderer (generated
// once from the spec templates by tools/gencodes): there are NO hand-written
// message strings anywhere in generated code — the single-renderer design is the
// strongest form of the four-target message-identity guarantee.
//
// Determinism: emission walks the schema in declaration order; regenerating
// twice is byte-identical (the emitter is strictspec's own canonical formatter —
// output is run through go/format).
package emit

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/smm-h/strictspec/go/internal/doc"
	"github.com/smm-h/strictspec/go/internal/schema"
)

// GoParams configures one Go emission.
type GoParams struct {
	Package          string            // generated package name
	MainFile         string            // key of the schema entry point within Files
	Files            map[string]string // embedded file set (schema + imports + scalars)
	GeneratorVersion string            // strictspec release doing the generation
	RegenCommand     string            // the exact command to regenerate (header + gate remediation)
}

// GeneratedFileName returns the conventional output file name for a schema.
func GeneratedFileName(s *schema.Schema) string {
	return sanitizeLower(s.Name) + "_gen.go"
}

// GenerateGo emits the generated Go validator source for schema s. s must be
// fully resolved (imports merged into s.Types); scalars is the bound custom
// scalar registry.
func GenerateGo(s *schema.Schema, scalars map[string]*schema.Scalar, p GoParams) (string, error) {
	g := &goEmitter{s: s, scalars: scalars, p: p}
	src := g.build()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("emit: generated Go did not format (emitter bug): %w\n%s", err, numbered(src))
	}
	return string(formatted), nil
}

type goEmitter struct {
	s       *schema.Schema
	scalars map[string]*schema.Scalar
	p       GoParams
	b       strings.Builder
}

func (g *goEmitter) build() string {
	g.header()
	g.embeddedFiles()
	g.programInit()
	g.entryPoints()
	g.types()
	g.bindHelpers()
	return g.b.String()
}

func (g *goEmitter) header() {
	w := &g.b
	fmt.Fprintf(w, "// Code generated by strictspec. DO NOT EDIT.\n")
	fmt.Fprintf(w, "//\n")
	fmt.Fprintf(w, "// strictspec generator: %s\n", g.p.GeneratorVersion)
	fmt.Fprintf(w, "// schema:              %s (format_version %d)\n", g.s.Name, g.s.FormatVersion)
	fmt.Fprintf(w, "// regenerate:          %s\n", g.p.RegenCommand)
	fmt.Fprintf(w, "//\n")
	fmt.Fprintf(w, "// Released under the MIT license (unencumbered). This file is machine-generated;\n")
	fmt.Fprintf(w, "// edit the schema and regenerate, never this file.\n")
	fmt.Fprintf(w, "package %s\n\n", g.p.Package)
	fmt.Fprintf(w, "import \"github.com/smm-h/strictspec/go/strictspec\"\n\n")
}

func (g *goEmitter) embeddedFiles() {
	w := &g.b
	fmt.Fprintf(w, "// GeneratedBy is the strictspec release that produced this file. The runtime\n")
	fmt.Fprintf(w, "// pairing guard hard-errors unless it matches the linked runtime exactly.\n")
	fmt.Fprintf(w, "const GeneratedBy = %q\n\n", g.p.GeneratorVersion)
	fmt.Fprintf(w, "// SchemaFormatVersion is the document format_version this validator accepts.\n")
	fmt.Fprintf(w, "const SchemaFormatVersion = %d\n\n", g.s.FormatVersion)

	// Embed each backing file. Sort keys for deterministic output.
	names := make([]string, 0, len(g.p.Files))
	for k := range g.p.Files {
		names = append(names, k)
	}
	sort.Strings(names)
	fmt.Fprintf(w, "// embeddedSchema carries the compiled schema (and its imported type-definition\n")
	fmt.Fprintf(w, "// files and scalar manifest) so the validator is self-contained and does no IO.\n")
	fmt.Fprintf(w, "var embeddedSchema = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(w, "\t%q: %s,\n", name, backtickLiteral(g.p.Files[name]))
	}
	fmt.Fprintf(w, "}\n\n")
	fmt.Fprintf(w, "const embeddedMainFile = %q\n\n", g.p.MainFile)
}

func (g *goEmitter) programInit() {
	w := &g.b
	fmt.Fprintf(w, "var program *strictspec.Program\n\n")
	fmt.Fprintf(w, "func init() {\n")
	fmt.Fprintf(w, "\t// Version pairing: generated code and runtime must be the same release.\n")
	fmt.Fprintf(w, "\tstrictspec.RequireRuntimeVersion(GeneratedBy)\n")
	fmt.Fprintf(w, "\tp, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)\n")
	fmt.Fprintf(w, "\tif err != nil {\n\t\tpanic(err)\n\t}\n")
	fmt.Fprintf(w, "\tprogram = p\n")
	fmt.Fprintf(w, "}\n\n")
}

func (g *goEmitter) entryPoints() {
	w := &g.b
	rootGo := g.exportType(g.s.Root)
	rootBind := "bind" + g.exportType(g.s.Root)
	rootIsRecord := g.isRecord(g.s.Root)
	ret := "strictspec.Value"
	if rootIsRecord {
		ret = "*" + rootGo
	}

	fmt.Fprintf(w, "// ValidateBytes is the raw-bytes entry point: lossless parse of input in the\n")
	fmt.Fprintf(w, "// given syntax (\"json\" | \"toml\" | \"jsonl\"), then validate. It returns the\n")
	fmt.Fprintf(w, "// typed root value (nil when any diagnostic fired) and the ordered diagnostics.\n")
	fmt.Fprintf(w, "func ValidateBytes(input []byte, syntax string) (%s, []strictspec.Diagnostic) {\n", ret)
	fmt.Fprintf(w, "\tres := program.Validate(input, syntax)\n")
	fmt.Fprintf(w, "\tif !res.Valid {\n\t\treturn nil, res.Diagnostics\n\t}\n")
	fmt.Fprintf(w, "\tv, err := strictspec.LoadValue(input, syntax)\n")
	fmt.Fprintf(w, "\tif err != nil {\n\t\treturn nil, res.Diagnostics\n\t}\n")
	if rootIsRecord {
		fmt.Fprintf(w, "\treturn %s(v), nil\n", rootBind)
	} else {
		fmt.Fprintf(w, "\treturn v, nil\n")
	}
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "// ValidateValue is the tagged-value entry point: validate an already-parsed\n")
	fmt.Fprintf(w, "// tagged document value (from strictspec.LoadValue or a typed constructor).\n")
	fmt.Fprintf(w, "func ValidateValue(v strictspec.Value) (%s, []strictspec.Diagnostic) {\n", ret)
	fmt.Fprintf(w, "\tres := program.ValidateValue(v)\n")
	fmt.Fprintf(w, "\tif !res.Valid {\n\t\treturn nil, res.Diagnostics\n\t}\n")
	if rootIsRecord {
		fmt.Fprintf(w, "\treturn %s(v), nil\n", rootBind)
	} else {
		fmt.Fprintf(w, "\treturn v, nil\n")
	}
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver\n")
	fmt.Fprintf(w, "// evidence for the phase-2 constraint vocabulary.\n")
	fmt.Fprintf(w, "func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (%s, []strictspec.Diagnostic) {\n", ret)
	fmt.Fprintf(w, "\tres := program.ValidateWithEvidence(input, syntax, evidence)\n")
	fmt.Fprintf(w, "\tif !res.Valid {\n\t\treturn nil, res.Diagnostics\n\t}\n")
	fmt.Fprintf(w, "\tv, err := strictspec.LoadValue(input, syntax)\n")
	fmt.Fprintf(w, "\tif err != nil {\n\t\treturn nil, res.Diagnostics\n\t}\n")
	if rootIsRecord {
		fmt.Fprintf(w, "\treturn %s(v), nil\n", rootBind)
	} else {
		fmt.Fprintf(w, "\treturn v, nil\n")
	}
	fmt.Fprintf(w, "}\n\n")
}

// types emits a frozen struct + binder + With* helpers for every named record
// type (including imported ones, which ResolveImports merged into s.Types but not
// s.TypeOrder), in a deterministic order: declared types first, then imported
// types alphabetically.
func (g *goEmitter) types() {
	for _, name := range g.typeOrder() {
		t := g.s.Types[name]
		if t == nil || t.Kind != schema.KindRecord {
			continue
		}
		g.recordType(name, t)
	}
}

// typeOrder returns every named type deterministically: the schema's declaration
// order first, then any remaining (imported) types sorted alphabetically.
func (g *goEmitter) typeOrder() []string {
	seen := map[string]bool{}
	order := make([]string, 0, len(g.s.Types))
	for _, name := range g.s.TypeOrder {
		if _, ok := g.s.Types[name]; ok && !seen[name] {
			order = append(order, name)
			seen[name] = true
		}
	}
	var rest []string
	for name := range g.s.Types {
		if !seen[name] {
			rest = append(rest, name)
		}
	}
	sort.Strings(rest)
	return append(order, rest...)
}

func (g *goEmitter) recordType(name string, t *schema.Type) {
	w := &g.b
	goName := g.exportType(name)
	fmt.Fprintf(w, "// %s is the frozen typed binding of the %q record. Fields are immutable by\n", goName, name)
	fmt.Fprintf(w, "// convention (shallow-plus-generated-immutability); use With* for copy-on-write.\n")
	fmt.Fprintf(w, "type %s struct {\n", goName)
	for _, f := range t.Fields {
		fmt.Fprintf(w, "\t%s %s\n", g.exportField(f.Name), g.goType(f.Type))
	}
	fmt.Fprintf(w, "}\n\n")

	// Binder.
	fmt.Fprintf(w, "func bind%s(v strictspec.Value) *%s {\n", goName, goName)
	fmt.Fprintf(w, "\tif v.Kind() != strictspec.KindRecord {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(w, "\tout := &%s{}\n", goName)
	for _, f := range t.Fields {
		fmt.Fprintf(w, "\tif fv, ok := v.Field(%q); ok {\n", f.Name)
		fmt.Fprintf(w, "\t\tout.%s = %s\n", g.exportField(f.Name), g.bindExpr(f.Type, "fv"))
		fmt.Fprintf(w, "\t}\n")
	}
	fmt.Fprintf(w, "\treturn out\n")
	fmt.Fprintf(w, "}\n\n")

	// With* helpers (per-field copy-on-write).
	for _, f := range t.Fields {
		fn := g.exportField(f.Name)
		gt := g.goType(f.Type)
		fmt.Fprintf(w, "// With%s returns a copy of %s with %s set to the given value.\n", fn, goName, fn)
		fmt.Fprintf(w, "func (x *%s) With%s(v %s) *%s {\n", goName, fn, gt, goName)
		fmt.Fprintf(w, "\tc := *x\n\tc.%s = v\n\treturn &c\n}\n\n", fn)
	}
}

// bindHelpers emits the generic slice/pointer binders the field binders call.
// They are package-level (unused ones are harmless) and generic, so one pair
// serves every array and nullable field.
func (g *goEmitter) bindHelpers() {
	w := &g.b
	fmt.Fprintf(w, "func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {\n")
	fmt.Fprintf(w, "\titems := v.Items()\n\tout := make([]T, len(items))\n")
	fmt.Fprintf(w, "\tfor i, e := range items {\n\t\tout[i] = f(e)\n\t}\n\treturn out\n}\n\n")
	fmt.Fprintf(w, "func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {\n")
	fmt.Fprintf(w, "\tif v.IsNull() {\n\t\treturn nil\n\t}\n\tt := f(v)\n\treturn &t\n}\n")
}

// goType maps a schema type site to its generated Go type. Named record types
// bind to *Struct; scalars to their Go primitive; arrays to slices; everything
// else (unions, tuples, opaque leaves, inline records, maps) to the tagged
// strictspec.Value (verbatim, consumer-dispatched) so generated code always
// compiles while the named-record layer stays fully typed.
func (g *goEmitter) goType(t *schema.Type) string {
	if t == nil {
		return "strictspec.Value"
	}
	switch t.Kind {
	case schema.KindRef:
		switch t.Ref {
		case "string":
			return "string"
		case "integer":
			return "int64"
		case "float", "number":
			return "float64"
		case "boolean":
			return "bool"
		case "date", "time", "datetime":
			// Bound to the retained lexeme string: no normalization on read
			// (a +00:00 offset is not rewritten to Z), per primitives item 11.
			return "string"
		default:
			if named, ok := g.s.Types[t.Ref]; ok {
				if named.Kind == schema.KindRecord {
					return "*" + g.exportType(t.Ref)
				}
				return g.goType(named)
			}
			// A custom scalar (base string) or an unresolved leaf.
			return "string"
		}
	case schema.KindArray:
		return "[]" + g.goType(t.Item)
	case schema.KindEnum:
		if g.intEnum(t) {
			return "int64"
		}
		return "string"
	case schema.KindLiteral:
		return goTypeOfKind(t.Literal.Kind)
	case schema.KindNullable:
		inner := g.goType(t.Inner)
		if strings.HasPrefix(inner, "*") || inner == "strictspec.Value" {
			return inner
		}
		return "*" + inner
	default:
		// record (inline), map, tuple, union, opaque.
		return "strictspec.Value"
	}
}

// bindExpr returns a Go expression binding valueVar (a strictspec.Value) to the
// Go type goType(t) produces.
func (g *goEmitter) bindExpr(t *schema.Type, valueVar string) string {
	if t == nil {
		return valueVar
	}
	switch t.Kind {
	case schema.KindRef:
		switch t.Ref {
		case "string":
			return coerce1(valueVar, "String")
		case "integer":
			return coerce1(valueVar, "Int")
		case "float":
			return coerce1(valueVar, "Float")
		case "number":
			return coerce1(valueVar, "Number")
		case "boolean":
			return coerce1(valueVar, "Bool")
		case "date", "time", "datetime":
			return coerce1(valueVar, "Datetime")
		default:
			if named, ok := g.s.Types[t.Ref]; ok {
				if named.Kind == schema.KindRecord {
					return fmt.Sprintf("bind%s(%s)", g.exportType(t.Ref), valueVar)
				}
				return g.bindExpr(named, valueVar)
			}
			return coerce1(valueVar, "String") // custom scalar
		}
	case schema.KindArray:
		return fmt.Sprintf("bindSlice(%s, func(e strictspec.Value) %s { return %s })",
			valueVar, g.goType(t.Item), g.bindExpr(t.Item, "e"))
	case schema.KindEnum:
		if g.intEnum(t) {
			return coerce1(valueVar, "Int")
		}
		return coerce1(valueVar, "String")
	case schema.KindLiteral:
		return coerce1(valueVar, coercerOfKind(t.Literal.Kind))
	case schema.KindNullable:
		inner := g.goType(t.Inner)
		if strings.HasPrefix(inner, "*") || inner == "strictspec.Value" {
			// Already nullable-capable.
			if inner == "strictspec.Value" {
				return valueVar
			}
			return g.bindExpr(t.Inner, valueVar)
		}
		return fmt.Sprintf("bindPtr(%s, func(e strictspec.Value) %s { return %s })",
			valueVar, inner, g.bindExpr(t.Inner, "e"))
	default:
		return valueVar // record/map/tuple/union/opaque: hold the tagged value verbatim
	}
}

// --- helpers ----------------------------------------------------------------

func coerce1(valueVar, method string) string {
	// The generated binder runs only after phase-1 validation established the
	// kind, so the coercer's ok is true; we take the value and drop ok.
	return fmt.Sprintf("func() %s { r, _ := %s.%s(); return r }()", coercerReturnType(method), valueVar, method)
}

func coercerReturnType(method string) string {
	switch method {
	case "Int":
		return "int64"
	case "Float", "Number":
		return "float64"
	case "Bool":
		return "bool"
	default: // String, Datetime
		return "string"
	}
}

func coercerOfKind(k doc.Kind) string {
	switch k {
	case doc.Integer:
		return "Int"
	case doc.Float:
		return "Float"
	case doc.Bool:
		return "Bool"
	default:
		return "String"
	}
}

func goTypeOfKind(k doc.Kind) string {
	switch k {
	case doc.Integer:
		return "int64"
	case doc.Float:
		return "float64"
	case doc.Bool:
		return "bool"
	default:
		return "string"
	}
}

func (g *goEmitter) intEnum(t *schema.Type) bool {
	if t.Sourced {
		return false
	}
	for _, ev := range t.EnumValues {
		if ev.Kind != doc.Integer {
			return false
		}
	}
	return len(t.EnumValues) > 0
}

func (g *goEmitter) isRecord(name string) bool {
	t, ok := g.s.Types[name]
	return ok && t != nil && t.Kind == schema.KindRecord
}

func (g *goEmitter) exportType(name string) string { return exportName(name) }

func (g *goEmitter) exportField(name string) string { return exportName(name) }

// exportName converts a schema identifier (Type name or snake_case field) into a
// Go-exported CamelCase identifier, deterministically.
func exportName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		r := []rune(p)
		b.WriteString(strings.ToUpper(string(r[0])))
		if len(r) > 1 {
			b.WriteString(string(r[1:]))
		}
	}
	out := b.String()
	if out == "" {
		return "Field"
	}
	// Ensure it starts with a letter.
	if c := out[0]; c >= '0' && c <= '9' {
		out = "X" + out
	}
	return out
}

func sanitizeLower(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + 32)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		return "schema"
	}
	return out
}

// backtickLiteral renders s as a Go raw string literal, falling back to a
// double-quoted literal when s contains a backtick (raw strings can't).
func backtickLiteral(s string) string {
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}

func numbered(src string) string {
	var b strings.Builder
	for i, line := range strings.Split(src, "\n") {
		fmt.Fprintf(&b, "%4d\t%s\n", i+1, line)
	}
	return b.String()
}
