package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenMultiTargetHygiene drives `strictspec gen` for a schema that declares
// go, python, AND ts targets, then asserts each generated file lands chmod 444,
// carries the target ecosystem's pinned generated-file/lint-suppression markers,
// and is registered in .gitattributes. A follow-up `check` must report fresh for
// every target (the drift gate covers all three).
func TestGenMultiTargetHygiene(t *testing.T) {
	dir := t.TempDir()
	schemasDir := filepath.Join(dir, "schemas")
	if err := os.MkdirAll(filepath.Join(dir, "gen"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(schemasDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// shared-canvas declares safe_integers = true (mandatory for a TS target) and
	// imports types-geometry, so it exercises the imported-file embedding path.
	copyFile(t, filepath.Join(fixturesSchemas(t), "shared-canvas.toml"), filepath.Join(schemasDir, "shared-canvas.toml"))
	copyFile(t, filepath.Join(fixturesSchemas(t), "types-geometry.toml"), filepath.Join(schemasDir, "types-geometry.toml"))

	manifest := filepath.Join(dir, "strictspec.toml")
	writeFile(t, manifest, `format_version = 1
[[schemas]]
path = "schemas/shared-canvas.toml"
  [[schemas.targets]]
  lang = "go"
  output = "gen/canvas_gen.go"
  package = "canvas"
  [[schemas.targets]]
  lang = "python"
  output = "gen/canvas_generated.py"
  [[schemas.targets]]
  lang = "ts"
  output = "gen/canvas.generated.ts"
`)

	if r := newApp().Test([]string{"gen", "--manifest", manifest}); r.ExitCode != 0 {
		t.Fatalf("gen exit = %d: %s", r.ExitCode, r.Stderr)
	}

	checks := []struct {
		path   string
		marker string
	}{
		{filepath.Join(dir, "gen", "canvas_gen.go"), "// Code generated by strictspec. DO NOT EDIT."},
		{filepath.Join(dir, "gen", "canvas_generated.py"), "# ruff: noqa"},
		{filepath.Join(dir, "gen", "canvas.generated.ts"), "/* eslint-disable */"},
	}
	for _, c := range checks {
		info, err := os.Stat(c.path)
		if err != nil {
			t.Fatalf("generated file missing: %v", err)
		}
		if info.Mode().Perm() != 0o444 {
			t.Errorf("%s mode = %v, want 0444 (chmod 444 hygiene)", c.path, info.Mode().Perm())
		}
		src, _ := os.ReadFile(c.path)
		if !strings.Contains(string(src), c.marker) {
			t.Errorf("%s missing marker %q", c.path, c.marker)
		}
	}

	// .gitattributes must register all three generated paths (LF + linguist-generated).
	ga, err := os.ReadFile(filepath.Join(dir, ".gitattributes"))
	if err != nil {
		t.Fatalf(".gitattributes missing: %v", err)
	}
	for _, want := range []string{"gen/canvas_gen.go", "gen/canvas_generated.py", "gen/canvas.generated.ts"} {
		if !strings.Contains(string(ga), want) {
			t.Errorf(".gitattributes missing entry for %q\n%s", want, ga)
		}
	}

	// check: fresh for all three targets.
	if r := newApp().Test([]string{"check", "--manifest", manifest}); r.ExitCode != 0 {
		t.Fatalf("check (fresh) exit = %d: %s", r.ExitCode, r.Stderr)
	}

	// Drift on the python target must be caught by check.
	pyPath := filepath.Join(dir, "gen", "canvas_generated.py")
	src, _ := os.ReadFile(pyPath)
	_ = os.Chmod(pyPath, 0o644)
	writeFile(t, pyPath, string(src)+"\n# tampered\n")
	_ = os.Chmod(pyPath, 0o444)
	if r := newApp().Test([]string{"check", "--manifest", manifest}); r.ExitCode == 0 {
		t.Fatal("check must fail on python drift")
	}
}

// TestGenTSWithoutSafeIntegersIsHardError asserts that declaring a TS target for a
// schema lacking `safe_integers = true` is a hard error at gen time, with the
// pinned catalogue message (ts/DESIGN.md — Numbers in TS).
func TestGenTSWithoutSafeIntegersIsHardError(t *testing.T) {
	dir := t.TempDir()
	schema := filepath.Join(dir, "tiny.schema.toml")
	writeFile(t, schema, `name = "Tiny"
meta_version = 1
format_version = 1
document_syntax = "json"
role = "schema"
root = "Tiny"

[types.Tiny]
type = "record"

[types.Tiny.fields.n]
type = "integer"
`)
	manifest := filepath.Join(dir, "strictspec.toml")
	writeFile(t, manifest, `format_version = 1
[[schemas]]
path = "tiny.schema.toml"
  [[schemas.targets]]
  lang = "ts"
  output = "tiny.generated.ts"
`)
	r := newApp().Test([]string{"gen", "--manifest", manifest})
	if r.ExitCode == 0 {
		t.Fatal("gen with a TS target and no safe_integers must hard-error")
	}
	if !strings.Contains(r.Stderr, "declares a TypeScript target but omits") {
		t.Errorf("expected the safe_integers hard-error message, got:\n%s", r.Stderr)
	}
}

// TestGenUnknownTargetIsHardError asserts an unknown target lang is a hard error.
func TestGenUnknownTargetIsHardError(t *testing.T) {
	dir := t.TempDir()
	schema := filepath.Join(dir, "tiny.schema.toml")
	writeFile(t, schema, `name = "Tiny"
meta_version = 1
format_version = 1
document_syntax = "json"
role = "schema"
root = "Tiny"

[types.Tiny]
type = "record"

[types.Tiny.fields.n]
type = "integer"
`)
	manifest := filepath.Join(dir, "strictspec.toml")
	writeFile(t, manifest, `format_version = 1
[[schemas]]
path = "tiny.schema.toml"
  [[schemas.targets]]
  lang = "rust"
  output = "tiny.rs"
`)
	r := newApp().Test([]string{"gen", "--manifest", manifest})
	if r.ExitCode == 0 {
		t.Fatal("gen with an unknown target lang must hard-error")
	}
	if !strings.Contains(r.Stderr, "unknown generation target") {
		t.Errorf("expected the unknown-target hard-error message, got:\n%s", r.Stderr)
	}
}
