package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// fixturesSchemas returns the conformance _schemas directory.
func fixturesSchemas(t *testing.T) string {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", "..", "conformance", "fixtures", "_schemas"))
}

// TestRegistration builds the app: strictcli validates every command, flag, and
// argument at registration time, so a misdeclared flag panics here. Reaching the
// end means registration-time conformance passed.
func TestRegistration(t *testing.T) {
	app := newApp()
	if app == nil {
		t.Fatal("newApp returned nil")
	}
}

func TestInitRefusesOverwrite(t *testing.T) {
	dir := t.TempDir()
	manifest := filepath.Join(dir, "strictspec.toml")
	if r := newApp().Test([]string{"init", "--manifest", manifest}); r.ExitCode != 0 {
		t.Fatalf("init exit = %d: %s", r.ExitCode, r.Stderr)
	}
	if _, err := os.Stat(manifest); err != nil {
		t.Fatalf("manifest not written: %v", err)
	}
	if r := newApp().Test([]string{"init", "--manifest", manifest}); r.ExitCode == 0 {
		t.Fatal("init must refuse to overwrite an existing manifest")
	}
}

func TestGenThenCheckFreshThenDrift(t *testing.T) {
	dir := t.TempDir()
	schemasDir := filepath.Join(dir, "schemas")
	if err := os.MkdirAll(filepath.Join(dir, "gen"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(schemasDir, 0o755); err != nil {
		t.Fatal(err)
	}
	copyFile(t, filepath.Join(fixturesSchemas(t), "shared-canvas.toml"), filepath.Join(schemasDir, "shared-canvas.toml"))
	copyFile(t, filepath.Join(fixturesSchemas(t), "types-geometry.toml"), filepath.Join(schemasDir, "types-geometry.toml"))

	manifest := filepath.Join(dir, "strictspec.toml")
	writeFile(t, manifest, `format_version = 1
[[schemas]]
path = "schemas/shared-canvas.toml"
  [[schemas.targets]]
  lang = "go"
  output = "gen/canvas_gen.go"
  package = "canvas"
`)

	if r := newApp().Test([]string{"gen", "--manifest", manifest}); r.ExitCode != 0 {
		t.Fatalf("gen exit = %d: %s", r.ExitCode, r.Stderr)
	}
	genPath := filepath.Join(dir, "gen", "canvas_gen.go")
	info, err := os.Stat(genPath)
	if err != nil {
		t.Fatalf("generated file missing: %v", err)
	}
	if info.Mode().Perm() != 0o444 {
		t.Errorf("generated file mode = %v, want 0444 (chmod 444 hygiene)", info.Mode().Perm())
	}
	src, _ := os.ReadFile(genPath)
	if !strings.Contains(string(src), "// Code generated by strictspec. DO NOT EDIT.") {
		t.Error("generated file missing the DO NOT EDIT marker")
	}

	// check: fresh.
	if r := newApp().Test([]string{"check", "--manifest", manifest}); r.ExitCode != 0 {
		t.Fatalf("check (fresh) exit = %d: %s", r.ExitCode, r.Stderr)
	}
	// tamper -> drift.
	_ = os.Chmod(genPath, 0o644)
	writeFile(t, genPath, string(src)+"\n// tampered\n")
	_ = os.Chmod(genPath, 0o444)
	if r := newApp().Test([]string{"check", "--manifest", manifest}); r.ExitCode == 0 {
		t.Fatal("check must fail on drift")
	}
}

func TestValidateRequiresMode(t *testing.T) {
	schema := filepath.Join(fixturesSchemas(t), "shared-canvas.toml")
	// No mode flag -> the required mutex rejects it (non-zero exit).
	r := newApp().Test([]string{"validate", schema, "/dev/null"})
	if r.ExitCode == 0 {
		t.Fatal("validate without --structural-only/--with-domain-checks must fail")
	}
}

func TestExportProducesJSONSchema(t *testing.T) {
	dir := t.TempDir()
	schema := filepath.Join(fixturesSchemas(t), "shared-canvas.toml")
	out := filepath.Join(dir, "canvas.schema.json")
	if r := newApp().Test([]string{"export", schema, "--output", out}); r.ExitCode != 0 {
		t.Fatalf("export exit = %d: %s", r.ExitCode, r.Stderr)
	}
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	s := string(b)
	if !strings.Contains(s, "json-schema.org") || !strings.Contains(s, "\"$defs\"") {
		t.Errorf("export output does not look like JSON Schema:\n%s", s[:min(len(s), 200)])
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func copyFile(t *testing.T, src, dst string) {
	t.Helper()
	b, err := os.ReadFile(src)
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, dst, string(b))
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
