#!/usr/bin/env node
// Generate the TypeScript module carrying strictspec's built-in schemas.
//
// The single source of every built-in schema is go/strictspec/builtin/*.schema.toml
// (the Go runtime embeds those files directly). This script emits
// src/builtins.generated.ts, holding each file's exact text as a string
// constant, and a freshness test regenerates and byte-compares (drift = test
// failure).
//
// Usage:
//   node scripts/genbuiltins.mjs [--check]
//
// --check regenerates in memory and exits non-zero if the on-disk file differs.

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE_REL = "go/strictspec/builtin";
const OUT_REL = "ts/src/builtins.generated.ts";

// [constant name, source file name], in emission order.
const BUILTINS = [
	["LIFECYCLE_AND_LICENSE_SCHEMA", "lifecycle-and-license.schema.toml"],
	["OPTIONS_ENTRIES_SCHEMA", "options-entries.schema.toml"],
	["OPTIONS_REGISTRY_SCHEMA", "options-registry.schema.toml"],
	["UPSTREAM_SCHEMA", "upstream.schema.toml"],
];

const repoRoot = fileURLToPath(new URL("../../", import.meta.url));

function generate() {
	const srcDir = join(repoRoot, SOURCE_REL);
	const names = readdirSync(srcDir)
		.filter((n) => n.endsWith(".schema.toml"))
		.sort();
	const declared = BUILTINS.map(([, f]) => f).sort();
	if (JSON.stringify(names) !== JSON.stringify(declared)) {
		throw new Error(
			`genbuiltins: ${SOURCE_REL} holds ${JSON.stringify(names)}, but BUILTINS declares ${JSON.stringify(declared)}; add or remove the matching BUILTINS row`,
		);
	}
	const out = [
		"/* eslint-disable */",
		"// Code generated by ts/scripts/genbuiltins.mjs from go/strictspec/builtin/. DO NOT EDIT.",
		"// The exact text of each strictspec built-in schema.",
		"",
	];
	for (const [name, file] of BUILTINS) {
		const text = readFileSync(join(srcDir, file), "utf-8");
		out.push(`// ${file}`);
		out.push(`export const ${name} = ${JSON.stringify(text)};`);
		out.push("");
	}
	return out.join("\n");
}

function main() {
	const content = generate();
	const outPath = join(repoRoot, OUT_REL);
	if (process.argv.includes("--check")) {
		const existing = existsSync(outPath) ? readFileSync(outPath, "utf-8") : "";
		if (existing !== content) {
			process.stderr.write(
				`genbuiltins: ${OUT_REL} is stale; regenerate with node ts/scripts/genbuiltins.mjs\n`,
			);
			process.exit(1);
		}
		return;
	}
	writeFileSync(outPath, content, "utf-8");
}

main();
