#!/usr/bin/env python3
"""Generate the Python module carrying strictspec's built-in schemas.

The single source of every built-in schema is go/strictspec/builtin/*.schema.toml
(the Go runtime embeds those files directly). This script emits
src/strictspec/_builtins.py, holding each file's exact text as a string
constant, and a freshness test regenerates and byte-compares (drift = test
failure).

Usage:
    python scripts/genbuiltins.py [--check]

--check regenerates in memory and exits non-zero if the on-disk file differs.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SOURCE_REL = "go/strictspec/builtin"
OUT_REL = "python/src/strictspec/_builtins.py"

# (constant name, source file name), in emission order.
BUILTINS = (
    ("OPTIONS_ENTRIES_SCHEMA", "options-entries.schema.toml"),
    ("OPTIONS_REGISTRY_SCHEMA", "options-registry.schema.toml"),
    ("UPSTREAM_SCHEMA", "upstream.schema.toml"),
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def generate(root: Path) -> str:
    src_dir = root / SOURCE_REL
    names = sorted(p.name for p in src_dir.glob("*.schema.toml"))
    declared = sorted(f for _, f in BUILTINS)
    if names != declared:
        raise SystemExit(
            f"genbuiltins: {SOURCE_REL} holds {names}, but BUILTINS declares {declared}; "
            "add or remove the matching BUILTINS row"
        )
    out = [
        "# ruff: noqa",
        "# Code generated by python/scripts/genbuiltins.py from go/strictspec/builtin/. DO NOT EDIT.",
        '"""The exact text of each strictspec built-in schema."""',
        "",
    ]
    for const, fname in BUILTINS:
        text = (src_dir / fname).read_text(encoding="utf-8")
        out.append(f"# {fname}")
        out.append(f"{const} = {text!r}")
        out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    root = repo_root()
    content = generate(root)
    out = root / OUT_REL
    if args.check:
        if not out.exists() or out.read_text(encoding="utf-8") != content:
            print(f"{OUT_REL} is stale; regenerate with python/scripts/genbuiltins.py", file=sys.stderr)
            return 1
        return 0
    out.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
