
[[releasables]]
name = "py-strictspec"

[[releasables]]
name = "go-strictspec"

[[releasables]]
name = "ts-strictspec"


[[projects]]
path = "python"
name = "strictspec"
releasable = "py-strictspec"
watch = ["python/**"]


[[projects]]
path = "go"
name = "go-strictspec"
releasable = "go-strictspec"


[[projects]]
path = "ts"
name = "ts-strictspec"
releasable = "ts-strictspec"

[[projects]]
path = "conformance/"
name = "conformance"
dev_only = true
releasable = false
watch = ["python/**", "go/**", "ts/**", "spec/**"]
