// Package strictspec: Define a schema once in TOML, and generate the full
// toolchain in your language: validation, versioning, migrations, etc. --
// First-class support for Go, Python, and TypeScript.
//
// This package is the public Go runtime: the schema toolchain turns one TOML
// schema into Go, Python and TypeScript validators reporting identical verdicts,
// error codes, paths and messages for JSON, TOML and JSONL files.
//
// This is the PUBLIC surface that generated strictspec validator code imports
// (go/DESIGN.md, "Runtime subpackage"). It is deliberately minimal and
// stable-facing — this surface becomes semver-bound at release. It re-exports the diagnostics model, document loading for the three
// syntaxes, the generated-code pairing guard, the tagged document value (the second
// entry point) with its coercers, and the constraint-engine entry (validation is
// driven by the shared emitter IR, internal/ir, so a generated Go validator runs
// the identical checks as the reference interpreter).
//
// Invariants (go/DESIGN.md): no lenient modes; loading and validation are
// inseparable; unknown keys are always a hard error; there is no severity — every
// diagnostic is an error; raw untagged maps are never a validation input (tagged
// values only).
package strictspec

import (
	"fmt"
	"strconv"

	ssroot "github.com/stricttools/strictspec/go"
)

// Version is the strictspec release this runtime was built at. It is embedded
// from the module-root VERSION file (via the strictspecroot package) — the same
// file rlsbl's Go release target bumps during `rlsbl release run`. It is
// INFORMATIONAL for generated code: pairing is on the generated-code format
// below, never on this string, so no tool may derive a dependency floor from the
// GENERATED_BY constant a generated file carries.
var Version = ssroot.Version

// MinGeneratedCodeFormat and MaxGeneratedCodeFormat are the inclusive range of
// generated-code formats this runtime reads. The generated-code format is an
// integer describing the SHAPE of emitted code — the constants it declares, the
// runtime calls it makes, the diagnostics it can produce — and it is bumped only
// when that shape changes, never on an ordinary release. Generated code declares
// the format it was written to; this runtime accepts it when the format is in
// this range, whatever release produced it.
const (
	MinGeneratedCodeFormat = 1
	MaxGeneratedCodeFormat = 2
)

// pairingMessage renders the one refusal text, shared by every entry point below
// and held byte-identical with the Python and TypeScript runtimes by the
// conformance suite.
func pairingMessage(format, generatedBy string) string {
	return fmt.Sprintf(
		"strictspec generated-code format mismatch:\n"+
			"  generated-code format: %s\n"+
			"  runtime reads:         %d..%d\n"+
			"  generated by:          %s\n"+
			"  runtime:               %s\n"+
			"  remediation:           regenerate with `strictspec gen` against the current runtime",
		format, MinGeneratedCodeFormat, MaxGeneratedCodeFormat, generatedBy, Version)
}

// CheckGeneratedCodeFormat reports whether generated code declaring
// generatedCodeFormat (its GENERATED_CODE_FORMAT constant) is paired with this
// runtime. generatedBy is the release that produced the file; it appears in the
// message as information and never affects the verdict. A format outside the
// accepted range returns a structured error whose remediation is regeneration.
func CheckGeneratedCodeFormat(generatedCodeFormat int, generatedBy string) error {
	if generatedCodeFormat >= MinGeneratedCodeFormat && generatedCodeFormat <= MaxGeneratedCodeFormat {
		return nil
	}
	return fmt.Errorf("%s", pairingMessage(strconv.Itoa(generatedCodeFormat), generatedBy))
}

// RequireGeneratedCodeFormat is the hard-error form used in generated init: it
// panics when the generated code's format is one this runtime does not read. A
// pairing mismatch is a build/deploy error, not a runtime condition, so it fails
// loudly.
func RequireGeneratedCodeFormat(generatedCodeFormat int, generatedBy string) {
	if err := CheckGeneratedCodeFormat(generatedCodeFormat, generatedBy); err != nil {
		panic(err.Error())
	}
}

// CheckRuntimeVersion is the entry point generated code written BEFORE the
// generated-code format declaration existed calls. Such a file declares no
// format, so there is nothing to pair: this always returns an error naming the
// absent declaration and the remedy. A format-less module is never read as
// format 1 — the consumer regenerates once.
func CheckRuntimeVersion(generatedBy string) error {
	return fmt.Errorf("%s", pairingMessage("absent (predates the format declaration)", generatedBy))
}

func RequireRuntimeVersion(generatedBy string) {
	if err := CheckRuntimeVersion(generatedBy); err != nil {
		panic(err.Error())
	}
}
