// Package strictspec is the PUBLIC Go runtime: the stable surface that generated
// strictspec validator code imports (go/DESIGN.md, "Runtime subpackage"). It is
// deliberately minimal and stable-facing — this surface becomes semver-bound at
// release. It re-exports the diagnostics model, document loading for the three
// syntaxes, the version-pairing guard, the tagged document value (the second
// entry point) with its coercers, and the constraint-engine entry (validation is
// driven by the shared emitter IR, internal/ir, so a generated Go validator runs
// the identical checks as the reference interpreter).
//
// Invariants (go/DESIGN.md): no lenient modes; loading and validation are
// inseparable; unknown keys are always a hard error; there is no severity — every
// diagnostic is an error; raw untagged maps are never a validation input (tagged
// values only).
package strictspec

import (
	"fmt"

	ssroot "github.com/smm-h/strictspec/go"
)

// Version is the strictspec release this runtime was built at. Generated code is
// paired to it exactly (see RequireRuntimeVersion). It is embedded from the
// module-root VERSION file (via the strictspecroot package) — the same file
// rlsbl's Go release target bumps during `rlsbl release run` — so the pairing
// constant can never drift from the released version. Dev builds carry whatever
// the working-tree VERSION file holds and pair only with matching artifacts;
// released and dev artifacts never cross-pair.
var Version = ssroot.Version

// CheckRuntimeVersion reports whether generated code pinned to generatedBy is
// paired with this runtime. Under the ecosystem's always-latest dependency rule
// this is the INTENDED surfacing of skew: the remediation is regeneration, never
// pinning. It returns a structured error (never nil-with-degradation) when the
// versions differ.
func CheckRuntimeVersion(generatedBy string) error {
	if generatedBy == Version {
		return nil
	}
	return fmt.Errorf(
		"strictspec version pairing mismatch:\n"+
			"  generated by: %s\n"+
			"  runtime:      %s\n"+
			"  remediation:  regenerate with `strictspec gen` against the current runtime "+
			"(do not pin — the always-latest rule surfaces skew so it gets fixed)",
		generatedBy, Version)
}

// RequireRuntimeVersion is the hard-error form used in generated init: it panics
// when generatedBy does not exactly match this runtime version. A pairing
// mismatch is a build/deploy error, not a runtime condition, so it fails loudly.
func RequireRuntimeVersion(generatedBy string) {
	if err := CheckRuntimeVersion(generatedBy); err != nil {
		panic(err.Error())
	}
}
