/* eslint-disable */
// The generated strictspec error-code catalogue.
//
// Code generated by scripts/gencodes.mjs from spec/appendix-error-codes.md. DO NOT EDIT.
//
// Every STRICTSPEC_* code with its area, message template, and declared slots,
// parsed from the single normative source. Hand-transcription is forbidden; a
// freshness test regenerates and byte-compares (drift = failure).

export enum SlotType {
	String = 0,
	Int = 1,
	Code = 2,
	Identifier = 3,
	Version = 4,
	Path = 5,
	Value = 6,
	List = 7,
}

export interface SlotSpec {
	readonly name: string;
	readonly type: SlotType;
	readonly elemType?: SlotType;
}

export interface Entry {
	readonly code: string;
	readonly area: string;
	readonly template: string;
	readonly slots: readonly SlotSpec[];
}

export function lookup(code: string): Entry | undefined {
	return CATALOGUE.get(code);
}

export function allEntries(): Entry[] {
	return [...CATALOGUE.keys()].sort().map((k) => CATALOGUE.get(k) as Entry);
}

// The closed area set (appendix-error-codes.md section 3).
export const AREAS: readonly string[] = [
	"ALIAS",
	"CHANNEL",
	"CROSS",
	"DEPTH",
	"DIFF",
	"DOCDIFF",
	"ENUMSRC",
	"GATE",
	"IMPORT",
	"INTRA",
	"KEY",
	"MANIFEST",
	"METAGATE",
	"MIGRATE",
	"NUM",
	"PARSE",
	"SCALAR",
	"SCHEMA",
	"SERIALIZE",
	"TYPE",
	"UNION",
	"VALUE",
];

export const CATALOGUE: Map<string, Entry> = new Map([
	[
		"STRICTSPEC_ALIAS_BOTH_PRESENT",
		{
			code: "STRICTSPEC_ALIAS_BOTH_PRESENT",
			area: "ALIAS",
			template: "Both {alias} and canonical {canonical} are present at {path}; provide exactly one.",
			slots: [
				{ name: "alias", type: SlotType.Identifier },
				{ name: "canonical", type: SlotType.Identifier },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_CHANNEL_VERSION_REFUSED",
		{
			code: "STRICTSPEC_CHANNEL_VERSION_REFUSED",
			area: "CHANNEL",
			template: "Cannot open channel for schema {schema}: peer offers `format_version` {got}, this endpoint speaks only {expected}. Update the client to the paired strictspec release ({release}).",
			slots: [
				{ name: "schema", type: SlotType.Identifier },
				{ name: "got", type: SlotType.Version },
				{ name: "expected", type: SlotType.Version },
				{ name: "release", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_CROSS_COLLECTION_UNIQUE",
		{
			code: "STRICTSPEC_CROSS_COLLECTION_UNIQUE",
			area: "CROSS",
			template: "Value {value} at {path} also appears in {source}; it must be unique across the collection family.",
			slots: [
				{ name: "value", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "source", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_CROSS_COUNT_LIMIT",
		{
			code: "STRICTSPEC_CROSS_COUNT_LIMIT",
			area: "CROSS",
			template: "Collection at {path} has {actual} elements across {source}; the limit is {limit}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.Int },
				{ name: "source", type: SlotType.String },
				{ name: "limit", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_CROSS_REFERENCE_UNRESOLVED",
		{
			code: "STRICTSPEC_CROSS_REFERENCE_UNRESOLVED",
			area: "CROSS",
			template: "Reference {value} at {path} does not resolve in {source}.",
			slots: [
				{ name: "value", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "source", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_CROSS_RESOLVER_UNAVAILABLE",
		{
			code: "STRICTSPEC_CROSS_RESOLVER_UNAVAILABLE",
			area: "CROSS",
			template: "Constraint at {path} requires evidence resolver {source}, which this environment cannot satisfy.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "source", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_CROSS_SET_COVERAGE",
		{
			code: "STRICTSPEC_CROSS_SET_COVERAGE",
			area: "CROSS",
			template: "Element {value} of {source} is not covered by the collection at {path}.",
			slots: [
				{ name: "value", type: SlotType.Value },
				{ name: "source", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_CROSS_SUM_FIELD_MISSING",
		{
			code: "STRICTSPEC_CROSS_SUM_FIELD_MISSING",
			area: "CROSS",
			template: "sum-limit at {path} over {source} requires numeric field {field} on every selected document; document {actual} lacks it or has a non-numeric value.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "source", type: SlotType.String },
				{ name: "field", type: SlotType.String },
				{ name: "actual", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_CROSS_SUM_LIMIT",
		{
			code: "STRICTSPEC_CROSS_SUM_LIMIT",
			area: "CROSS",
			template: "Sum of {field} across {source} at {path} is {actual}; the limit is {limit}.",
			slots: [
				{ name: "field", type: SlotType.String },
				{ name: "source", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.Value },
				{ name: "limit", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_DEPTH_EXCEEDED",
		{
			code: "STRICTSPEC_DEPTH_EXCEEDED",
			area: "DEPTH",
			template: "Document nesting at {path} exceeds the maximum validation depth of {limit}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "limit", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_DIFF_ADJUDICATION_INVALID",
		{
			code: "STRICTSPEC_DIFF_ADJUDICATION_INVALID",
			area: "DIFF",
			template: "Adjudication file {source} does not validate against the adjudication schema: {detail}.",
			slots: [
				{ name: "source", type: SlotType.String },
				{ name: "detail", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_DIFF_ADJUDICATION_MISSING",
		{
			code: "STRICTSPEC_DIFF_ADJUDICATION_MISSING",
			area: "DIFF",
			template: "Claim {condition} is corpus-supported without a corpus, and no adjudication entry covers it.",
			slots: [
				{ name: "condition", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_DIFF_CORPUS_EMPTY",
		{
			code: "STRICTSPEC_DIFF_CORPUS_EMPTY",
			area: "DIFF",
			template: "The corpus glob {source} resolved to zero documents; `diff` requires a non-empty corpus.",
			slots: [
				{ name: "source", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_DIFF_NARROWING_UNBUMPED",
		{
			code: "STRICTSPEC_DIFF_NARROWING_UNBUMPED",
			area: "DIFF",
			template: "Document {source} is valid under the old schema but invalid under the new schema at the same `format_version` {expected}; this narrowing requires a version bump.",
			slots: [
				{ name: "source", type: SlotType.String },
				{ name: "expected", type: SlotType.Version },
			],
		},
	],
	[
		"STRICTSPEC_DIFF_TAXONOMY_MISDECLARED",
		{
			code: "STRICTSPEC_DIFF_TAXONOMY_MISDECLARED",
			area: "DIFF",
			template: "Op {op} is declared {expected} but the corpus shows it is {actual}.",
			slots: [
				{ name: "op", type: SlotType.String },
				{ name: "expected", type: SlotType.String },
				{ name: "actual", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_DIFF_VIOLATED",
		{
			code: "STRICTSPEC_DIFF_VIOLATED",
			area: "DIFF",
			template: "Claim {condition} is VIOLATED: corpus document {source} is a counterexample.",
			slots: [
				{ name: "condition", type: SlotType.String },
				{ name: "source", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_DOCDIFF_INVALID_OPERAND",
		{
			code: "STRICTSPEC_DOCDIFF_INVALID_OPERAND",
			area: "DOCDIFF",
			template: "Operand {source} does not validate against the schema; `doc-diff` compares valid documents.",
			slots: [
				{ name: "source", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_DOCDIFF_SCHEMA_MISMATCH",
		{
			code: "STRICTSPEC_DOCDIFF_SCHEMA_MISMATCH",
			area: "DOCDIFF",
			template: "Documents {source} and {actual} do not share `format_version`; `doc-diff` compares documents of one schema at one version.",
			slots: [
				{ name: "source", type: SlotType.String },
				{ name: "actual", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_ENUMSRC_BAD_SELECTOR",
		{
			code: "STRICTSPEC_ENUMSRC_BAD_SELECTOR",
			area: "ENUMSRC",
			template: "Enum-source selector {selector} at {path} does not resolve within {source}.",
			slots: [
				{ name: "selector", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "source", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_ENUMSRC_MISSING_SOURCE",
		{
			code: "STRICTSPEC_ENUMSRC_MISSING_SOURCE",
			area: "ENUMSRC",
			template: "Enum at {path} sources arms from {source}, which does not exist.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "source", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_ENUMSRC_SOURCE_NOT_STRINGS",
		{
			code: "STRICTSPEC_ENUMSRC_SOURCE_NOT_STRINGS",
			area: "ENUMSRC",
			template: "Enum source {source} at {path} yields a non-string arm; sourced enum arms must be strings.",
			slots: [
				{ name: "source", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_ENUMSRC_STALE",
		{
			code: "STRICTSPEC_ENUMSRC_STALE",
			area: "ENUMSRC",
			template: "Baked enum arms at {path} differ from source {source}; regenerate with `strictspec gen`. Baked: {baked}. Source: {actual}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "source", type: SlotType.String },
				{ name: "baked", type: SlotType.List, elemType: SlotType.String },
				{ name: "actual", type: SlotType.List, elemType: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_GATE_ABSENT",
		{
			code: "STRICTSPEC_GATE_ABSENT",
			area: "GATE",
			template: "Document is missing `format_version`. Schema {schema} expects {expected}. Run: {invocation}",
			slots: [
				{ name: "schema", type: SlotType.Identifier },
				{ name: "expected", type: SlotType.Version },
				{ name: "invocation", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_GATE_UNSUPPORTED",
		{
			code: "STRICTSPEC_GATE_UNSUPPORTED",
			area: "GATE",
			template: "Document `format_version` is {got}, but schema {schema} accepts exactly {expected} (migration set {migset}). Run: {invocation}",
			slots: [
				{ name: "got", type: SlotType.Version },
				{ name: "schema", type: SlotType.Identifier },
				{ name: "expected", type: SlotType.Version },
				{ name: "migset", type: SlotType.Identifier },
				{ name: "invocation", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_GATE_WRONG_TYPE",
		{
			code: "STRICTSPEC_GATE_WRONG_TYPE",
			area: "GATE",
			template: "Document `format_version` must be an integer; got {got}. Schema {schema} expects {expected}. Run: {invocation}",
			slots: [
				{ name: "got", type: SlotType.Value },
				{ name: "schema", type: SlotType.Identifier },
				{ name: "expected", type: SlotType.Version },
				{ name: "invocation", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_IMPORT_CROSS_FILE_CONSTRAINT",
		{
			code: "STRICTSPEC_IMPORT_CROSS_FILE_CONSTRAINT",
			area: "IMPORT",
			template: "Imported file {file} declares a constraint; type-definition files may declare types only, not constraints.",
			slots: [
				{ name: "file", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_IMPORT_MISSING_TYPE_FILE",
		{
			code: "STRICTSPEC_IMPORT_MISSING_TYPE_FILE",
			area: "IMPORT",
			template: "Type-definition file {file} imported by {schema} does not exist.",
			slots: [
				{ name: "file", type: SlotType.String },
				{ name: "schema", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_IMPORT_TRANSITIVE",
		{
			code: "STRICTSPEC_IMPORT_TRANSITIVE",
			area: "IMPORT",
			template: "Type-definition file {file} imports another file; transitive imports are not permitted.",
			slots: [
				{ name: "file", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_IMPORT_UNKNOWN_TYPE",
		{
			code: "STRICTSPEC_IMPORT_UNKNOWN_TYPE",
			area: "IMPORT",
			template: "Type {name} is not defined in imported file {file}.",
			slots: [
				{ name: "name", type: SlotType.Identifier },
				{ name: "file", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_AT_LEAST_ONE_OF",
		{
			code: "STRICTSPEC_INTRA_AT_LEAST_ONE_OF",
			area: "INTRA",
			template: "At least one of {fields} must be present at {path}; none were.",
			slots: [
				{ name: "fields", type: SlotType.List, elemType: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_COLLECTIONS_DISJOINT",
		{
			code: "STRICTSPEC_INTRA_COLLECTIONS_DISJOINT",
			area: "INTRA",
			template: "Arrays {fields} at {path} must share no element; {value} appears in both (normalization: {normalization}).",
			slots: [
				{ name: "fields", type: SlotType.List, elemType: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "value", type: SlotType.Value },
				{ name: "normalization", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_CONDITIONAL_REQUIRED",
		{
			code: "STRICTSPEC_INTRA_CONDITIONAL_REQUIRED",
			area: "INTRA",
			template: "Field {key} at {path} is required when {condition}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "condition", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_CONDITIONAL_VALUE",
		{
			code: "STRICTSPEC_INTRA_CONDITIONAL_VALUE",
			area: "INTRA",
			template: "Field {key} at {path} must equal {expected} when {condition}; got {got}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.Value },
				{ name: "condition", type: SlotType.String },
				{ name: "got", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_CO_PRESENCE",
		{
			code: "STRICTSPEC_INTRA_CO_PRESENCE",
			area: "INTRA",
			template: "Fields {fields} at {path} must be present together or absent together; found {actual}.",
			slots: [
				{ name: "fields", type: SlotType.List, elemType: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.List, elemType: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_EXACTLY_ONE_OF",
		{
			code: "STRICTSPEC_INTRA_EXACTLY_ONE_OF",
			area: "INTRA",
			template: "Exactly one of {fields} must be present at {path}; found {actual}.",
			slots: [
				{ name: "fields", type: SlotType.List, elemType: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.List, elemType: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_FORBIDDEN_WHEN",
		{
			code: "STRICTSPEC_INTRA_FORBIDDEN_WHEN",
			area: "INTRA",
			template: "Field {key} at {path} is forbidden when {condition}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "condition", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_MUTUAL_EXCLUSION",
		{
			code: "STRICTSPEC_INTRA_MUTUAL_EXCLUSION",
			area: "INTRA",
			template: "Fields {fields} at {path} are mutually exclusive; found {actual}.",
			slots: [
				{ name: "fields", type: SlotType.List, elemType: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.List, elemType: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_ORDERED_PAIR",
		{
			code: "STRICTSPEC_INTRA_ORDERED_PAIR",
			area: "INTRA",
			template: "Field {actual} at {path} must be less than sibling {value}.",
			slots: [
				{ name: "actual", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "value", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_PAIRWISE_DISTINCT",
		{
			code: "STRICTSPEC_INTRA_PAIRWISE_DISTINCT",
			area: "INTRA",
			template: "Values at {path} must be pairwise distinct; {value} repeats (normalization: {normalization}).",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "value", type: SlotType.Value },
				{ name: "normalization", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_RANGES_DISJOINT",
		{
			code: "STRICTSPEC_INTRA_RANGES_DISJOINT",
			area: "INTRA",
			template: "Half-open ranges at {path} overlap: {value} intersects {actual}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "value", type: SlotType.Value },
				{ name: "actual", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_REFERENCE_UNRESOLVED",
		{
			code: "STRICTSPEC_INTRA_REFERENCE_UNRESOLVED",
			area: "INTRA",
			template: "Reference {value} at {path} does not resolve within the document.",
			slots: [
				{ name: "value", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_INTRA_UNIQUE_BY",
		{
			code: "STRICTSPEC_INTRA_UNIQUE_BY",
			area: "INTRA",
			template: "Duplicate value {value} for unique-by {field} at {path} (normalization: {normalization}).",
			slots: [
				{ name: "value", type: SlotType.Value },
				{ name: "field", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "normalization", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_KEY_DUPLICATE",
		{
			code: "STRICTSPEC_KEY_DUPLICATE",
			area: "KEY",
			template: "Duplicate key {key} at {path}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_KEY_UNKNOWN",
		{
			code: "STRICTSPEC_KEY_UNKNOWN",
			area: "KEY",
			template: "Unknown key {key} at {path}.{suggestion}",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "suggestion", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_MANIFEST_ALREADY_EXISTS",
		{
			code: "STRICTSPEC_MANIFEST_ALREADY_EXISTS",
			area: "MANIFEST",
			template: "A `strictspec.toml` already exists at {path}; `strictspec init` refuses to overwrite it.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_MANIFEST_DRIFT",
		{
			code: "STRICTSPEC_MANIFEST_DRIFT",
			area: "MANIFEST",
			template: "Generated output at {path} differs from a fresh generation; run `strictspec gen` and commit.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_MANIFEST_GENERATED_PATH_DIRTY",
		{
			code: "STRICTSPEC_MANIFEST_GENERATED_PATH_DIRTY",
			area: "MANIFEST",
			template: "Generated path {path} has uncommitted local edits; regenerate before proceeding.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_MANIFEST_PAIRING_MISMATCH",
		{
			code: "STRICTSPEC_MANIFEST_PAIRING_MISMATCH",
			area: "MANIFEST",
			template: "Runtime version {actual} does not match generated-code version {expected}; regenerate against the paired release.",
			slots: [
				{ name: "actual", type: SlotType.Version },
				{ name: "expected", type: SlotType.Version },
			],
		},
	],
	[
		"STRICTSPEC_MANIFEST_UNKNOWN_RESOLVER",
		{
			code: "STRICTSPEC_MANIFEST_UNKNOWN_RESOLVER",
			area: "MANIFEST",
			template: "Manifest / schema references evidence resolver {name}, which is not in the resolver vocabulary.",
			slots: [
				{ name: "name", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_MANIFEST_UNKNOWN_STORE",
		{
			code: "STRICTSPEC_MANIFEST_UNKNOWN_STORE",
			area: "MANIFEST",
			template: "Manifest declares store {name}, whose kind {got} is not a recognized store kind.",
			slots: [
				{ name: "name", type: SlotType.Identifier },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_METAGATE_ABSENT",
		{
			code: "STRICTSPEC_METAGATE_ABSENT",
			area: "METAGATE",
			template: "Schema {schema} is missing `meta_version`. This strictspec release expects {expected}. Run: {invocation}",
			slots: [
				{ name: "schema", type: SlotType.Identifier },
				{ name: "expected", type: SlotType.Version },
				{ name: "invocation", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_METAGATE_UNSUPPORTED",
		{
			code: "STRICTSPEC_METAGATE_UNSUPPORTED",
			area: "METAGATE",
			template: "Schema {schema} declares `meta_version` {got}, but this strictspec release supports {expected}. Run: {invocation}",
			slots: [
				{ name: "schema", type: SlotType.Identifier },
				{ name: "got", type: SlotType.Version },
				{ name: "expected", type: SlotType.Version },
				{ name: "invocation", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_METAGATE_WRONG_TYPE",
		{
			code: "STRICTSPEC_METAGATE_WRONG_TYPE",
			area: "METAGATE",
			template: "Schema `meta_version` must be an integer; got {got}.",
			slots: [
				{ name: "got", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_COLLISION",
		{
			code: "STRICTSPEC_MIGRATE_COLLISION",
			area: "MIGRATE",
			template: "Migration op {op} would write {path}, which already exists.",
			slots: [
				{ name: "op", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_IRREVERSIBLE_DOWN",
		{
			code: "STRICTSPEC_MIGRATE_IRREVERSIBLE_DOWN",
			area: "MIGRATE",
			template: "Op {op} at {path} is declared irreversible; a down-migration was requested.",
			slots: [
				{ name: "op", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_ON_CURRENT",
		{
			code: "STRICTSPEC_MIGRATE_ON_CURRENT",
			area: "MIGRATE",
			template: "Document at {path} is already at the current `format_version` {expected}; nothing to migrate.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.Version },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_PREDICATE_UNSUPPORTED",
		{
			code: "STRICTSPEC_MIGRATE_PREDICATE_UNSUPPORTED",
			area: "MIGRATE",
			template: "Predicate at {path} tests more than equality and presence; migration predicates are restricted.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_REVALIDATION_FAILED",
		{
			code: "STRICTSPEC_MIGRATE_REVALIDATION_FAILED",
			area: "MIGRATE",
			template: "Migrated document at {path} does not validate at `format_version` {expected}; the migration is unsound.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.Version },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_TARGET_MISSING",
		{
			code: "STRICTSPEC_MIGRATE_TARGET_MISSING",
			area: "MIGRATE",
			template: "Migration op {op} targets {path}, which is absent in the document.",
			slots: [
				{ name: "op", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_TYPE_MISMATCH",
		{
			code: "STRICTSPEC_MIGRATE_TYPE_MISMATCH",
			area: "MIGRATE",
			template: "Migration op {op} at {path} expected {expected}, found {got}.",
			slots: [
				{ name: "op", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.String },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_UNKNOWN_SET",
		{
			code: "STRICTSPEC_MIGRATE_UNKNOWN_SET",
			area: "MIGRATE",
			template: "No migration set {migset} is registered for schema {schema}.",
			slots: [
				{ name: "migset", type: SlotType.Identifier },
				{ name: "schema", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_MIGRATE_UNWRAP_NOT_SINGLETON",
		{
			code: "STRICTSPEC_MIGRATE_UNWRAP_NOT_SINGLETON",
			area: "MIGRATE",
			template: "unwrap_singleton at {path} requires a single-element array; found {actual} elements.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_NUM_FLOAT_OVERFLOW",
		{
			code: "STRICTSPEC_NUM_FLOAT_OVERFLOW",
			area: "NUM",
			template: "Float lexeme {actual} at {path} is beyond float64 range.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_NUM_INT_OVERFLOW",
		{
			code: "STRICTSPEC_NUM_INT_OVERFLOW",
			area: "NUM",
			template: "Integer lexeme {actual} at {path} overflows int64.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_NUM_NON_FINITE",
		{
			code: "STRICTSPEC_NUM_NON_FINITE",
			area: "NUM",
			template: "Non-finite number {actual} at {path} is not permitted.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_NUM_SAFE_INTEGER",
		{
			code: "STRICTSPEC_NUM_SAFE_INTEGER",
			area: "NUM",
			template: "Integer {actual} at {path} exceeds the safe-integer range (|n| >= 2^53) required by `safe_integers`.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_NUM_UNREPRESENTABLE",
		{
			code: "STRICTSPEC_NUM_UNREPRESENTABLE",
			area: "NUM",
			template: "Lexeme {actual} at {path} cannot be represented exactly as float64; the `number` scalar refuses silent precision loss.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_JSONL_BLANK_LINE",
		{
			code: "STRICTSPEC_PARSE_JSONL_BLANK_LINE",
			area: "PARSE",
			template: "Blank line {line} is not a valid JSONL document.",
			slots: [
				{ name: "line", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_JSONL_DUPLICATE_KEY",
		{
			code: "STRICTSPEC_PARSE_JSONL_DUPLICATE_KEY",
			area: "PARSE",
			template: "Duplicate key {key} on JSONL line {line} at {path}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "line", type: SlotType.Int },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_JSONL_LINE_SYNTAX",
		{
			code: "STRICTSPEC_PARSE_JSONL_LINE_SYNTAX",
			area: "PARSE",
			template: "JSONL parse error on line {line} at {path}: {detail}.",
			slots: [
				{ name: "line", type: SlotType.Int },
				{ name: "path", type: SlotType.Path },
				{ name: "detail", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_JSONL_TRAILING_CR",
		{
			code: "STRICTSPEC_PARSE_JSONL_TRAILING_CR",
			area: "PARSE",
			template: "Line {line} ends with a carriage return; JSONL is LF-only.",
			slots: [
				{ name: "line", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_JSON_DUPLICATE_KEY",
		{
			code: "STRICTSPEC_PARSE_JSON_DUPLICATE_KEY",
			area: "PARSE",
			template: "Duplicate key {key} in JSON object at {path}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_JSON_EMPTY",
		{
			code: "STRICTSPEC_PARSE_JSON_EMPTY",
			area: "PARSE",
			template: "Empty input: expected a JSON document, found none.",
			slots: [],
		},
	],
	[
		"STRICTSPEC_PARSE_JSON_SYNTAX",
		{
			code: "STRICTSPEC_PARSE_JSON_SYNTAX",
			area: "PARSE",
			template: "JSON parse error at {path}: {detail}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "detail", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_JSON_TRAILING",
		{
			code: "STRICTSPEC_PARSE_JSON_TRAILING",
			area: "PARSE",
			template: "Trailing content after the JSON document at {path}.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_TOML_DUPLICATE_KEY",
		{
			code: "STRICTSPEC_PARSE_TOML_DUPLICATE_KEY",
			area: "PARSE",
			template: "Duplicate key {key} in TOML table at {path}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_PARSE_TOML_EMPTY",
		{
			code: "STRICTSPEC_PARSE_TOML_EMPTY",
			area: "PARSE",
			template: "Empty TOML input: expected a document, found none.",
			slots: [],
		},
	],
	[
		"STRICTSPEC_PARSE_TOML_SYNTAX",
		{
			code: "STRICTSPEC_PARSE_TOML_SYNTAX",
			area: "PARSE",
			template: "TOML parse error at {path}: {detail}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "detail", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_SCALAR_BASE_MISMATCH",
		{
			code: "STRICTSPEC_SCALAR_BASE_MISMATCH",
			area: "SCALAR",
			template: "Value at {path} is not a {expected} lexeme, which the {name} scalar refines.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.String },
				{ name: "name", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_SCALAR_LENGTH",
		{
			code: "STRICTSPEC_SCALAR_LENGTH",
			area: "SCALAR",
			template: "Value at {path} violates the {name} scalar's length bound ({actual}, limit {limit}).",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "name", type: SlotType.Identifier },
				{ name: "actual", type: SlotType.Int },
				{ name: "limit", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_SCALAR_LEXEME",
		{
			code: "STRICTSPEC_SCALAR_LEXEME",
			area: "SCALAR",
			template: "Value {actual} at {path} does not match the {name} scalar's lexeme rule {pattern}.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "name", type: SlotType.Identifier },
				{ name: "pattern", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_SCALAR_NO_BINDING",
		{
			code: "STRICTSPEC_SCALAR_NO_BINDING",
			area: "SCALAR",
			template: "Custom scalar {name} declares no binding for target {got}; every declared target requires a binding.",
			slots: [
				{ name: "name", type: SlotType.Identifier },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_SCALAR_UNKNOWN",
		{
			code: "STRICTSPEC_SCALAR_UNKNOWN",
			area: "SCALAR",
			template: "Field {path} uses custom scalar {name}, which is not registered in the manifest.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "name", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_ALIAS_ON_DISCRIMINATOR",
		{
			code: "STRICTSPEC_SCHEMA_ALIAS_ON_DISCRIMINATOR",
			area: "SCHEMA",
			template: "Alias {alias} targets discriminator field {path}; a discriminator may not be aliased.",
			slots: [
				{ name: "alias", type: SlotType.Identifier },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_DATETIME_KIND_MISMATCH",
		{
			code: "STRICTSPEC_SCHEMA_DATETIME_KIND_MISMATCH",
			area: "SCHEMA",
			template: "Datetime range at {path} compares an offset scalar with a local scalar; comparisons must be same-kind.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_DEFAULT_KEY",
		{
			code: "STRICTSPEC_SCHEMA_DEFAULT_KEY",
			area: "SCHEMA",
			template: "The `default` key is not a construct of strictspec (field {path}); remove it. A typed value never carries data the author did not write.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_MISSING_FORMAT_VERSION",
		{
			code: "STRICTSPEC_SCHEMA_MISSING_FORMAT_VERSION",
			area: "SCHEMA",
			template: "Schema {schema} does not declare `format_version`.",
			slots: [
				{ name: "schema", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_MISSING_META_VERSION",
		{
			code: "STRICTSPEC_SCHEMA_MISSING_META_VERSION",
			area: "SCHEMA",
			template: "Schema {schema} does not declare `meta_version`.",
			slots: [
				{ name: "schema", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_NODE_KIND_UNION_AMBIGUOUS",
		{
			code: "STRICTSPEC_SCHEMA_NODE_KIND_UNION_AMBIGUOUS",
			area: "SCHEMA",
			template: "Undiscriminated union at {path} has two arms of the same node kind ({kind}); same-kind arms require a discriminator.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "kind", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_OPAQUE_NO_STANCE",
		{
			code: "STRICTSPEC_SCHEMA_OPAQUE_NO_STANCE",
			area: "SCHEMA",
			template: "Opaque JSON leaf {path} declares neither `consumer_check` nor `unchecked`; one is required.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_REGEX_UNSUPPORTED",
		{
			code: "STRICTSPEC_SCHEMA_REGEX_UNSUPPORTED",
			area: "SCHEMA",
			template: "Regex at {path} uses a feature outside the RE2-compatible subset: {detail}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "detail", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_TOML_NULLABLE",
		{
			code: "STRICTSPEC_SCHEMA_TOML_NULLABLE",
			area: "SCHEMA",
			template: "A nullable union is reachable at {path}, but the target document syntax is TOML; TOML models absence as an optional field.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_TS_WITHOUT_SAFE_INTEGERS",
		{
			code: "STRICTSPEC_SCHEMA_TS_WITHOUT_SAFE_INTEGERS",
			area: "SCHEMA",
			template: "Schema {schema} declares a TypeScript target but omits `safe_integers = true`; a TS target requires it.",
			slots: [
				{ name: "schema", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_TUPLE_ARRAY_BOUNDS",
		{
			code: "STRICTSPEC_SCHEMA_TUPLE_ARRAY_BOUNDS",
			area: "SCHEMA",
			template: "Field {path} declares both tuple form and array-length bounds; the two are mutually exclusive.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_UNCHECKED_NO_REASON",
		{
			code: "STRICTSPEC_SCHEMA_UNCHECKED_NO_REASON",
			area: "SCHEMA",
			template: "Leaf {path} declares `unchecked = true` without the mandatory `unchecked_reason`.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_UNKNOWN_META_KEY",
		{
			code: "STRICTSPEC_SCHEMA_UNKNOWN_META_KEY",
			area: "SCHEMA",
			template: "Unknown meta-schema key {key} at {path}.{suggestion}",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "suggestion", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_SCHEMA_UNKNOWN_TYPE_REF",
		{
			code: "STRICTSPEC_SCHEMA_UNKNOWN_TYPE_REF",
			area: "SCHEMA",
			template: "Field {path} references named type {name}, which is not declared or imported.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "name", type: SlotType.Identifier },
			],
		},
	],
	[
		"STRICTSPEC_SERIALIZE_NONCURRENT",
		{
			code: "STRICTSPEC_SERIALIZE_NONCURRENT",
			area: "SERIALIZE",
			template: "Refusing to serialize document at {path}: its `format_version` is {got}, but schema {schema} serializes only the current {expected}. Migrate before writing.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.Version },
				{ name: "schema", type: SlotType.Identifier },
				{ name: "expected", type: SlotType.Version },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_DATETIME_KIND",
		{
			code: "STRICTSPEC_TYPE_DATETIME_KIND",
			area: "TYPE",
			template: "Expected a {expected} datetime at {path}; got a {got} datetime.",
			slots: [
				{ name: "expected", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_MISMATCH",
		{
			code: "STRICTSPEC_TYPE_MISMATCH",
			area: "TYPE",
			template: "Expected {expected} at {path}, got {got}.",
			slots: [
				{ name: "expected", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_MISSING_REQUIRED",
		{
			code: "STRICTSPEC_TYPE_MISSING_REQUIRED",
			area: "TYPE",
			template: "Missing required field {key} at {path}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_ARRAY",
		{
			code: "STRICTSPEC_TYPE_NOT_ARRAY",
			area: "TYPE",
			template: "Expected an array at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_BOOLEAN",
		{
			code: "STRICTSPEC_TYPE_NOT_BOOLEAN",
			area: "TYPE",
			template: "Expected a boolean at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_DATE",
		{
			code: "STRICTSPEC_TYPE_NOT_DATE",
			area: "TYPE",
			template: "Expected a date at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_DATETIME",
		{
			code: "STRICTSPEC_TYPE_NOT_DATETIME",
			area: "TYPE",
			template: "Expected a datetime at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_ENUM_MEMBER",
		{
			code: "STRICTSPEC_TYPE_NOT_ENUM_MEMBER",
			area: "TYPE",
			template: "Value {got} at {path} is not one of {expected}.{suggestion}",
			slots: [
				{ name: "got", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.List, elemType: SlotType.String },
				{ name: "suggestion", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_FLOAT",
		{
			code: "STRICTSPEC_TYPE_NOT_FLOAT",
			area: "TYPE",
			template: "Expected a float at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_INTEGER",
		{
			code: "STRICTSPEC_TYPE_NOT_INTEGER",
			area: "TYPE",
			template: "Expected an integer at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_LITERAL",
		{
			code: "STRICTSPEC_TYPE_NOT_LITERAL",
			area: "TYPE",
			template: "Expected the literal {expected} at {path}, got {got}.",
			slots: [
				{ name: "expected", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_MAP",
		{
			code: "STRICTSPEC_TYPE_NOT_MAP",
			area: "TYPE",
			template: "Expected a map at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_RECORD",
		{
			code: "STRICTSPEC_TYPE_NOT_RECORD",
			area: "TYPE",
			template: "Expected a record at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_STRING",
		{
			code: "STRICTSPEC_TYPE_NOT_STRING",
			area: "TYPE",
			template: "Expected a string at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_NOT_TIME",
		{
			code: "STRICTSPEC_TYPE_NOT_TIME",
			area: "TYPE",
			template: "Expected a time at {path}, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_TYPE_TUPLE_ARITY",
		{
			code: "STRICTSPEC_TYPE_TUPLE_ARITY",
			area: "TYPE",
			template: "Tuple at {path} expects {expected} elements, got {got}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.Int },
				{ name: "got", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_UNION_DISCRIMINATOR_MISSING",
		{
			code: "STRICTSPEC_UNION_DISCRIMINATOR_MISSING",
			area: "UNION",
			template: "Missing discriminator {key} at {path}; expected one of {expected}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.List, elemType: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_UNION_DISCRIMINATOR_UNKNOWN",
		{
			code: "STRICTSPEC_UNION_DISCRIMINATOR_UNKNOWN",
			area: "UNION",
			template: "Discriminator {got} at {path} is not one of {expected}.{suggestion}",
			slots: [
				{ name: "got", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "expected", type: SlotType.List, elemType: SlotType.String },
				{ name: "suggestion", type: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_UNION_NODE_KIND",
		{
			code: "STRICTSPEC_UNION_NODE_KIND",
			area: "UNION",
			template: "No union arm at {path} accepts a {got}; expected one of {expected}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "got", type: SlotType.String },
				{ name: "expected", type: SlotType.List, elemType: SlotType.String },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_ARRAY_TOO_LONG",
		{
			code: "STRICTSPEC_VALUE_ARRAY_TOO_LONG",
			area: "VALUE",
			template: "Array at {path} has {actual} elements; maximum is {limit}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.Int },
				{ name: "limit", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_ARRAY_TOO_SHORT",
		{
			code: "STRICTSPEC_VALUE_ARRAY_TOO_SHORT",
			area: "VALUE",
			template: "Array at {path} has {actual} elements; minimum is {limit}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.Int },
				{ name: "limit", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_DATETIME_AFTER",
		{
			code: "STRICTSPEC_VALUE_DATETIME_AFTER",
			area: "VALUE",
			template: "Datetime {actual} at {path} is after the maximum {limit}.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "limit", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_DATETIME_BEFORE",
		{
			code: "STRICTSPEC_VALUE_DATETIME_BEFORE",
			area: "VALUE",
			template: "Datetime {actual} at {path} is before the minimum {limit}.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "limit", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_MAP_KEY_REGEX",
		{
			code: "STRICTSPEC_VALUE_MAP_KEY_REGEX",
			area: "VALUE",
			template: "Map key {key} at {path} does not match the required key pattern {pattern}.",
			slots: [
				{ name: "key", type: SlotType.String },
				{ name: "path", type: SlotType.Path },
				{ name: "pattern", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_NUM_TOO_LARGE",
		{
			code: "STRICTSPEC_VALUE_NUM_TOO_LARGE",
			area: "VALUE",
			template: "Value {actual} at {path} is above the maximum {limit}.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "limit", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_NUM_TOO_LARGE_EXCLUSIVE",
		{
			code: "STRICTSPEC_VALUE_NUM_TOO_LARGE_EXCLUSIVE",
			area: "VALUE",
			template: "Value {actual} at {path} must be less than {limit}.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "limit", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_NUM_TOO_SMALL",
		{
			code: "STRICTSPEC_VALUE_NUM_TOO_SMALL",
			area: "VALUE",
			template: "Value {actual} at {path} is below the minimum {limit}.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "limit", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_NUM_TOO_SMALL_EXCLUSIVE",
		{
			code: "STRICTSPEC_VALUE_NUM_TOO_SMALL_EXCLUSIVE",
			area: "VALUE",
			template: "Value {actual} at {path} must be greater than {limit}.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "limit", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_STRING_EMPTY",
		{
			code: "STRICTSPEC_VALUE_STRING_EMPTY",
			area: "VALUE",
			template: "String at {path} is empty; a non-empty value is required.",
			slots: [
				{ name: "path", type: SlotType.Path },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_STRING_REGEX",
		{
			code: "STRICTSPEC_VALUE_STRING_REGEX",
			area: "VALUE",
			template: "String {actual} at {path} does not match the required pattern {pattern}.",
			slots: [
				{ name: "actual", type: SlotType.Value },
				{ name: "path", type: SlotType.Path },
				{ name: "pattern", type: SlotType.Value },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_STRING_TOO_LONG",
		{
			code: "STRICTSPEC_VALUE_STRING_TOO_LONG",
			area: "VALUE",
			template: "String at {path} has {actual} code points; maximum is {limit}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.Int },
				{ name: "limit", type: SlotType.Int },
			],
		},
	],
	[
		"STRICTSPEC_VALUE_STRING_TOO_SHORT",
		{
			code: "STRICTSPEC_VALUE_STRING_TOO_SHORT",
			area: "VALUE",
			template: "String at {path} has {actual} code points; minimum is {limit}.",
			slots: [
				{ name: "path", type: SlotType.Path },
				{ name: "actual", type: SlotType.Int },
				{ name: "limit", type: SlotType.Int },
			],
		},
	],
]);
