// strictspec -- the public TypeScript runtime.
//
// The stable surface that generated strictspec validator code imports. It
// re-exports the diagnostics model, document loading for the three syntaxes, the
// version-pairing guard, the tagged document value (the second entry point) with
// its coercers, and the constraint-engine entry (validation is driven by the
// shared emitter IR, so a generated TS validator runs the identical checks as the
// reference interpreter and the Go/Python runtimes).
//
// Per ts/DESIGN.md the raw-text entry point takes RAW TEXT (never JSON.parse):
// the lossless parsers classify lexemes and produce tagged document values. There
// are no lenient modes; loading and validation are inseparable; unknown keys are
// always a hard error; there is no severity -- every diagnostic is an error; raw
// untagged JS objects are never a validation input (tagged values only).

import * as diagMod from "./diag.js";
import * as doc from "./doc.js";
import { Kind as DocKind, type Node, ParseError } from "./doc.js";
import * as ir from "./ir.js";
import * as jsondoc from "./jsondoc.js";
import * as render from "./render.js";
import * as schema from "./schema.js";
import { decodeJSON, decodeTOML } from "./strdecode.js";
import * as tomldoc from "./tomldoc.js";
import { VERSION } from "./version.js";

export { VERSION };
export type Syntax = "json" | "toml" | "jsonl";

// --- version pairing ---------------------------------------------------------

export class PairingError extends Error {
	constructor(message: string) {
		super(message);
		this.name = "PairingError";
	}
}

// Return a structured remediation message if generated code pinned to generatedBy
// is not paired with this runtime, else null. Under the always-latest dependency
// rule this is the INTENDED surfacing of skew: the remediation is regeneration,
// never pinning.
export function checkRuntimeVersion(generatedBy: string): string | null {
	if (generatedBy === VERSION) {
		return null;
	}
	return (
		"strictspec version pairing mismatch:\n" +
		`  generated by: ${generatedBy}\n` +
		`  runtime:      ${VERSION}\n` +
		"  remediation:  regenerate with `strictspec gen` against the current runtime " +
		"(do not pin -- the always-latest rule surfaces skew so it gets fixed)"
	);
}

// Hard-error form used in generated init: throw PairingError when generatedBy does
// not exactly match this runtime version.
export function requireRuntimeVersion(generatedBy: string): void {
	const msg = checkRuntimeVersion(generatedBy);
	if (msg !== null) {
		throw new PairingError(msg);
	}
}

// --- public result types -----------------------------------------------------

// One validation error: a stable STRICTSPEC_* code, the rendered path, and the
// pinned message text. There is no severity field: every diagnostic is an error.
export interface Diagnostic {
	readonly code: string;
	readonly path: string;
	readonly message: string;
}

// A validation outcome: whether the document validated, and the ordered
// diagnostics (empty iff valid). Diagnostics are in emission order. Frozen.
export interface Result {
	readonly valid: boolean;
	readonly diagnostics: readonly Diagnostic[];
}

// The lexeme class of a tagged document value (the public projection).
export enum Kind {
	Record = 0,
	Array = 1,
	String = 2,
	Integer = 3,
	Float = 4,
	Bool = 5,
	Null = 6,
	Datetime = 7,
	Date = 8,
	Time = 9,
}

// The structured outcome of the inline version gate: whether the document's
// format_version is accepted, plus the remediation payload on failure.
export interface GateResult {
	readonly ok: boolean;
	readonly diagnostics: readonly Diagnostic[];
}

// --- Program -----------------------------------------------------------------

// A compiled strictspec schema. Generated code builds one at import from its
// embedded schema (compileFromSource) and calls validate.
export class Program {
	private readonly prog: ir.Program;

	constructor(prog: ir.Program) {
		this.prog = prog;
	}

	// RAW-TEXT entry point: lossless parse of rawText in the given syntax
	// ("json" | "toml" | "jsonl"), then validate. Loading and validation are
	// inseparable. For JSONL every line is validated with per-line anchors.
	validate(rawText: string, syntax: Syntax): Result {
		return this.validateWithEvidence(rawText, syntax, null);
	}

	validateWithEvidence(
		rawText: string,
		syntax: Syntax,
		evidence: ir.Evidence | null,
	): Result {
		let diags: diagMod.Diagnostic[];
		if (syntax === "jsonl") {
			diags = this.validateJsonl(new TextEncoder().encode(rawText), evidence);
		} else if (syntax === "toml") {
			try {
				const d = tomldoc.parse(rawText);
				diags = ir.execute(
					this.prog,
					d.root,
					withEvidence({ format: doc.FORMAT_TOML }, evidence),
				);
			} catch (e) {
				diags = [parseDiag(asParseError(e))];
			}
		} else {
			try {
				const d = jsondoc.parse(new TextEncoder().encode(rawText));
				diags = ir.execute(
					this.prog,
					d.root,
					withEvidence({ format: doc.FORMAT_JSON }, evidence),
				);
			} catch (e) {
				diags = [parseDiag(asParseError(e))];
			}
		}
		return renderResult(diags);
	}

	// TAGGED-VALUE entry point: validate an already-parsed tagged document value
	// (from loadValue or a generated typed constructor). Raw untagged JS objects
	// are never accepted.
	validateValue(v: Value): Result {
		return this.validateValueWithEvidence(v, null);
	}

	validateValueWithEvidence(v: Value, evidence: ir.Evidence | null): Result {
		const diags = ir.execute(
			this.prog,
			v.node,
			withEvidence({ format: v.fmt }, evidence),
		);
		return renderResult(diags);
	}

	// Run ONLY the version gate against the document, returning its structured
	// result (the three-message pattern + remediation payload).
	gateOnly(rawText: string, syntax: Syntax): GateResult {
		let root: Node | null;
		let fmt: string;
		try {
			if (syntax === "toml") {
				root = tomldoc.parse(rawText).root;
				fmt = doc.FORMAT_TOML;
			} else if (syntax === "jsonl") {
				const docs = jsondoc.parseLines(new TextEncoder().encode(rawText));
				root = docs.length > 0 ? (docs[0] as doc.Document).root : null;
				fmt = doc.FORMAT_JSONL;
			} else {
				root = jsondoc.parse(new TextEncoder().encode(rawText)).root;
				fmt = doc.FORMAT_JSON;
			}
		} catch (e) {
			const r = renderResult([parseDiag(asParseError(e))]);
			return { ok: false, diagnostics: r.diagnostics };
		}
		const [ok, diags] = ir.runGate(this.prog, root, { format: fmt });
		return { ok, diagnostics: renderResult(diags).diagnostics };
	}

	private validateJsonl(
		src: Uint8Array,
		evidence: ir.Evidence | null,
	): diagMod.Diagnostic[] {
		let docs: doc.Document[];
		try {
			docs = jsondoc.parseLines(src);
		} catch (e) {
			return [parseDiag(asParseError(e))];
		}
		const starts = lineStarts(src);
		const out: diagMod.Diagnostic[] = [];
		docs.forEach((d, i) => {
			const ls = i < starts.length ? (starts[i] as number) : 0;
			out.push(
				...ir.execute(
					this.prog,
					d.root,
					withEvidence(
						{
							format: doc.FORMAT_JSONL,
							jsonl: true,
							line: i + 1,
							lineStart: ls,
						},
						evidence,
					),
				),
			);
		});
		return out;
	}
}

// Compile a schema carried IN MEMORY by generated code: files maps each
// referenced file name (the schema, imported type-definition files, and the
// scalar manifest) to its exact text, and mainFile names the entry point. Import
// resolution and custom-scalar binding happen against the FileSet, never disk. A
// schema-authoring problem throws.
export function compileFromSource(
	files: schema.FileSet,
	mainFile: string,
): Program {
	const [s, sdiags0] = schema.parseFrom(files, mainFile);
	const sdiags = [...sdiags0, ...schema.resolveImportsFrom(s, files)];
	if (sdiags.length > 0) {
		throw new Error(embeddedSchemaError(sdiags));
	}
	const scalars = schema.loadManifestScalarsFrom(files);
	return new Program(ir.compileProgram(s, scalars));
}

// --- tagged Value ------------------------------------------------------------

// One ordered key/value binding of a record or map.
export interface KV {
	readonly key: string;
	readonly value: Value;
}

// A TAGGED, lexeme-retaining document value: the second entry point's input and
// what generated typed constructors bind from. It comes from a lossless parse
// (loadValue) or from generated typed constructors. Raw untagged JS objects are
// never Values -- ambiguity never enters the model.
export class Value {
	readonly node: Node | null;
	readonly fmt: string;

	constructor(node: Node | null, fmt: string) {
		this.node = node;
		this.fmt = fmt;
	}

	kind(): Kind {
		if (this.node === null) {
			return Kind.Null;
		}
		switch (this.node.kind) {
			case DocKind.Record:
				return Kind.Record;
			case DocKind.Array:
				return Kind.Array;
			case DocKind.String:
				return Kind.String;
			case DocKind.Integer:
				return Kind.Integer;
			case DocKind.Float:
				return Kind.Float;
			case DocKind.Bool:
				return Kind.Bool;
			case DocKind.Null:
				return Kind.Null;
			case DocKind.DateTimeOffset:
			case DocKind.DateTimeLocal:
				return Kind.Datetime;
			case DocKind.DateLocal:
				return Kind.Date;
			case DocKind.TimeLocal:
				return Kind.Time;
			default:
				return Kind.Null;
		}
	}

	field(name: string): [Value, boolean] {
		if (this.node === null || this.node.kind !== DocKind.Record) {
			return [new Value(null, this.fmt), false];
		}
		for (const e of this.node.entries) {
			if (e.key === name) {
				return [new Value(e.value, this.fmt), true];
			}
		}
		return [new Value(null, this.fmt), false];
	}

	entries(): KV[] {
		if (this.node === null || this.node.kind !== DocKind.Record) {
			return [];
		}
		return this.node.entries.map((e) => ({
			key: e.key,
			value: new Value(e.value, this.fmt),
		}));
	}

	items(): Value[] {
		if (this.node === null || this.node.kind !== DocKind.Array) {
			return [];
		}
		return this.node.items.map((it) => new Value(it, this.fmt));
	}

	// --- coercers ------------------------------------------------------------

	string(): [string, boolean] {
		if (this.node === null || this.node.kind !== DocKind.String) {
			return ["", false];
		}
		return [this.decodeString(), true];
	}

	int(): [number, boolean] {
		if (this.node === null || this.node.kind !== DocKind.Integer) {
			return [0, false];
		}
		const v = schema.goParseInt(this.node.lexeme);
		if (v === null) {
			return [0, false];
		}
		return [Number(v), true];
	}

	float(): [number, boolean] {
		if (this.node === null || this.node.kind !== DocKind.Float) {
			return [0, false];
		}
		const f = schema.goParseFloat(this.node.lexeme);
		if (f === null) {
			return [0, false];
		}
		return [f, true];
	}

	number(): [number, boolean] {
		if (
			this.node === null ||
			(this.node.kind !== DocKind.Integer && this.node.kind !== DocKind.Float)
		) {
			return [0, false];
		}
		const f = schema.goParseFloat(this.node.lexeme);
		if (f === null) {
			return [0, false];
		}
		return [f, true];
	}

	bool(): [boolean, boolean] {
		if (this.node === null || this.node.kind !== DocKind.Bool) {
			return [false, false];
		}
		return [this.node.lexeme === "true", true];
	}

	datetime(): [string, boolean] {
		if (this.node === null) {
			return ["", false];
		}
		const k = this.node.kind;
		if (
			k === DocKind.DateTimeOffset ||
			k === DocKind.DateTimeLocal ||
			k === DocKind.DateLocal ||
			k === DocKind.TimeLocal
		) {
			return [this.node.lexeme, true];
		}
		if (k === DocKind.String) {
			return [this.decodeString(), true];
		}
		return ["", false];
	}

	isNull(): boolean {
		return this.node === null || this.node.kind === DocKind.Null;
	}

	private decodeString(): string {
		if (this.node === null) {
			return "";
		}
		if (this.fmt === doc.FORMAT_TOML) {
			return decodeTOML(this.node.lexeme);
		}
		return decodeJSON(this.node.lexeme);
	}
}

// Losslessly parse raw text in the given syntax into a tagged Value. For "jsonl"
// it parses the FIRST line (use loadValues for a stream). A parse failure throws
// -- there is no lenient mode.
export function loadValue(rawText: string, syntax: Syntax): Value {
	if (syntax === "toml") {
		const d = tomldoc.parse(rawText);
		return new Value(d.root, doc.FORMAT_TOML);
	}
	if (syntax === "jsonl") {
		const docs = jsondoc.parseLines(new TextEncoder().encode(rawText));
		if (docs.length === 0) {
			throw new Error("strictspec: empty JSONL stream");
		}
		return new Value((docs[0] as doc.Document).root, doc.FORMAT_JSONL);
	}
	const d = jsondoc.parse(new TextEncoder().encode(rawText));
	return new Value(d.root, doc.FORMAT_JSON);
}

// Losslessly parse a JSONL stream into one Value per line.
export function loadValues(rawText: string): Value[] {
	const docs = jsondoc.parseLines(new TextEncoder().encode(rawText));
	return docs.map((d) => new Value(d.root, doc.FORMAT_JSONL));
}

// Run ONLY the version gate against the document. A convenience for consumers that
// want to surface the gate verdict before full validation.
export function versionGate(
	program: Program,
	rawText: string,
	syntax: Syntax,
): GateResult {
	return program.gateOnly(rawText, syntax);
}

// --- internal helpers --------------------------------------------------------

function withEvidence(
	base: ir.ExecOptions,
	evidence: ir.Evidence | null,
): ir.ExecOptions {
	if (evidence === null) {
		return base;
	}
	return { ...base, evidence };
}

function renderResult(diags: diagMod.Diagnostic[]): Result {
	const out: Diagnostic[] = diags.map((d) => ({
		code: d.code,
		path: d.path.render(),
		message: render.render(d),
	}));
	return Object.freeze({
		valid: out.length === 0,
		diagnostics: Object.freeze(out),
	});
}

function asParseError(e: unknown): ParseError {
	if (e instanceof ParseError) {
		return e;
	}
	throw e;
}

function parseDiag(pe: ParseError): diagMod.Diagnostic {
	let code = "STRICTSPEC_PARSE_JSON_SYNTAX";
	if (pe.format === doc.FORMAT_TOML) {
		code = "STRICTSPEC_PARSE_TOML_SYNTAX";
	} else if (pe.format === doc.FORMAT_JSONL) {
		code = "STRICTSPEC_PARSE_JSONL_LINE_SYNTAX";
	}
	const slots: Record<string, diagMod.Slot> = {
		detail: diagMod.slotString(pe.detail),
	};
	// Only the JSONL line-syntax template carries a {line} placeholder; binding it
	// for JSON/TOML would be an unknown-slot render error.
	if (code === "STRICTSPEC_PARSE_JSONL_LINE_SYNTAX") {
		slots.line = diagMod.slotInt(pe.position.line);
	}
	return diagMod.newDiagnostic(code, diagMod.newPath(), slots);
}

function lineStarts(src: Uint8Array): number[] {
	const starts = [0];
	for (let i = 0; i < src.length; i++) {
		if (src[i] === 0x0a) {
			starts.push(i + 1);
		}
	}
	return starts;
}

function embeddedSchemaError(diags: diagMod.Diagnostic[]): string {
	const parts = [
		"strictspec: embedded schema failed meta-schema validation (regenerate):",
	];
	for (const d of diags) {
		parts.push(`\n  ${d.code} at ${d.path.render()}`);
	}
	return parts.join("");
}
